## COGS Transform Demonstrator:

**Description:** *This basic Jupyter Notebook is intended to demonstrate the end-to-end process using a number of defined steps. These steps do not need to be coupled within a single Notebook.*

***Note:*** *Sections of this transform are not yet fully developed; some developer first cut / hacks are present.*

**Status:** *Prototype Version 2.2.0.*

**Authour:** *Martyn Spooner.*

**Create Date:** *1st February 2020 (late 2019 component protobook pre-date this).*

***Revision History:***
* *1.x.x - Various hacked pieces of independent code eg: GoodTables CSVWLib etc. - M. Spooner Late 2019.*
* *2.0.0 - Packaging of 'hacked work pieces' into an end-to-end process - M. Spooner 1st February 2020.*
* *2.1.0 - Re-housing of core code components to a module - M. Spooner 12th February 2020.*
* *2.2.0 - Codelist recommendation component(s) & RDF creation refactoring - M. Spooner 26th February 2020.*

### Section: Define and Load into Memory Notebook Python Libraries / Components:

In [1]:
# Imports:

!pip install gssutils
from gssutils import *

# In development Transform Library to aid transforms:
import COGSTransformPack

# DataFrames!
import pandas as pd

# Useful for testing etc.
import numpy as np

# Do not display warnings:
import warnings
warnings.filterwarnings('ignore')

from IPython.core.display import display, HTML

#%load_ext autoreload # For Development Purposes...
#%autoreload 2 # For Development Purposes...

Requirement already satisfied: gssutils in /anaconda3/lib/python3.7/site-packages (0.5.12)
Requirement already satisfied: pyexcel-ods3 in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.5.3)
Requirement already satisfied: python-dateutil in /anaconda3/lib/python3.7/site-packages (from gssutils) (2.6.1)
Requirement already satisfied: pyexcel-io in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.5.20)
Requirement already satisfied: argparse in /anaconda3/lib/python3.7/site-packages (from gssutils) (1.4.0)
Requirement already satisfied: databaker in /anaconda3/lib/python3.7/site-packages (from gssutils) (2.0.0)
Requirement already satisfied: CacheControl in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.12.5)
Requirement already satisfied: requests in /anaconda3/lib/python3.7/site-packages (from gssutils) (2.18.4)
Requirement already satisfied: wheel in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.33.4)
Requirement already satisfied: unidecode in /anaconda3/lib/python3.7/site-packages (from gssutils) (1.1.1)
Requirement already satisfied: messytables in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.15.1)
Requirement already satisfied: xypath==1.1.1 in /anaconda3/lib/python3.7/site-packages (from gssutils) (1.1.1)
Requirement already satisfied: rdflib in /anaconda3/lib/python3.7/site-packages (from gssutils) (4.2.2)
Requirement already satisfied: pyexcel in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.5.15)
Requirement already satisfied: rdflib-jsonld in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.4.0)
Requirement already satisfied: lockfile in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.12.2)
Requirement already satisfied: pandas in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.24.2)
Requirement already satisfied: pyexcel-xls in /anaconda3/lib/python3.7/site-packages (from gssutils) (0.5.8)
Requirement already satisfied: ipython in /anaconda3/lib/python3.7/site-packages (from gssutils) (7.6.1)
Requirement already satisfied: html2text in /anaconda3/lib/python3.7/site-packages (from gssutils) (2019.8.11)
Requirement already satisfied: lxml in /anaconda3/lib/python3.7/site-packages (from gssutils) (4.3.4)
Requirement already satisfied: pyexcel-ezodf>=0.3.3 in /anaconda3/lib/python3.7/site-packages (from pyexcel-ods3->gssutils) (0.3.4)
Requirement already satisfied: six>=1.5 in /anaconda3/lib/python3.7/site-packages (from python-dateutil->gssutils) (1.12.0)
Requirement already satisfied: lml>=0.0.4 in /anaconda3/lib/python3.7/site-packages (from pyexcel-io->gssutils) (0.0.9)
Requirement already satisfied: docopt in /anaconda3/lib/python3.7/site-packages (from databaker->gssutils) (0.6.2)
Requirement already satisfied: pyhamcrest in /anaconda3/lib/python3.7/site-packages (from databaker->gssutils) (1.9.0)
Requirement already satisfied: xlutils in /anaconda3/lib/python3.7/site-packages (from databaker->gssutils) (2.0.0)
Requirement already satisfied: msgpack in /anaconda3/lib/python3.7/site-packages (from CacheControl->gssutils) (0.6.1)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests->gssutils) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests->gssutils) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests->gssutils) (3.0.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests->gssutils) (1.22)
Requirement already satisfied: xlrd>=0.8.0 in /anaconda3/lib/python3.7/site-packages (from messytables->gssutils) (1.2.0)
Requirement already satisfied: html5lib in /anaconda3/lib/python3.7/site-packages (from messytables->gssutils) (1.0.1)
Requirement already satisfied: json-table-schema<=0.2.1,>=0.2 in /anaconda3/lib/python3.7/site-packages (from messytables->gssutils) (0.2.1)
Requirement already satisfied: python-magic>=0.4.12 in /anaconda3/lib/python3.7/site-packages (from messytables->gssutils) (0.4.15)
Requirement already satisfied: isodate in /anaconda3/lib/python3.7/site-packages (from rdflib->gssutils) (0.6.0)
Requirement already satisfied: pyparsing in /anaconda3/lib/python3.7/site-packages (from rdflib->gssutils) (2.4.0)
Requirement already satisfied: texttable>=0.8.2 in /anaconda3/lib/python3.7/site-packages (from pyexcel->gssutils) (1.6.2)
Requirement already satisfied: pytz>=2011k in /anaconda3/lib/python3.7/site-packages (from pandas->gssutils) (2019.1)
Requirement already satisfied: numpy>=1.12.0 in /anaconda3/lib/python3.7/site-packages (from pandas->gssutils) (1.16.4)
Requirement already satisfied: xlwt in /anaconda3/lib/python3.7/site-packages (from pyexcel-xls->gssutils) (1.3.0)
Requirement already satisfied: jedi>=0.10 in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (0.13.3)
Requirement already satisfied: pickleshare in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (2.0.9)
Requirement already satisfied: traitlets>=4.2 in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (4.3.2)
Requirement already satisfied: pygments in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (2.4.2)
Requirement already satisfied: setuptools>=18.5 in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (41.0.1)
Requirement already satisfied: decorator in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (4.4.0)
Requirement already satisfied: backcall in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (0.1.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (0.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /anaconda3/lib/python3.7/site-packages (from ipython->gssutils) (4.7.0)
Requirement already satisfied: webencodings in /anaconda3/lib/python3.7/site-packages (from html5lib->messytables->gssutils) (0.5.1)
Requirement already satisfied: parso>=0.3.0 in /anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython->gssutils) (0.5.0)
Requirement already satisfied: wcwidth in /anaconda3/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->gssutils) (0.1.7)
Requirement already satisfied: ipython-genutils in /anaconda3/lib/python3.7/site-packages (from traitlets>=4.2->ipython->gssutils) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython->gssutils) (0.6.0)
Requirement already satisfied: csvwlib in /anaconda3/lib/python3.7/site-packages (0.2.3)
Requirement already satisfied: rdflib==4.2.2 in /anaconda3/lib/python3.7/site-packages (from csvwlib) (4.2.2)
Requirement already satisfied: language-tags==0.4.3 in /anaconda3/lib/python3.7/site-packages (from csvwlib) (0.4.3)
Requirement already satisfied: python-dateutil==2.6.1 in /anaconda3/lib/python3.7/site-packages (from csvwlib) (2.6.1)
Requirement already satisfied: requests==2.18.4 in /anaconda3/lib/python3.7/site-packages (from csvwlib) (2.18.4)
Requirement already satisfied: rdflib-jsonld==0.4.0 in /anaconda3/lib/python3.7/site-packages (from csvwlib) (0.4.0)
Requirement already satisfied: uritemplate==3.0.0 in /anaconda3/lib/python3.7/site-packages (from csvwlib) (3.0.0)
Requirement already satisfied: pyparsing in /anaconda3/lib/python3.7/site-packages (from rdflib==4.2.2->csvwlib) (2.4.0)
Requirement already satisfied: isodate in /anaconda3/lib/python3.7/site-packages (from rdflib==4.2.2->csvwlib) (0.6.0)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from language-tags==0.4.3->csvwlib) (1.12.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests==2.18.4->csvwlib) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests==2.18.4->csvwlib) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests==2.18.4->csvwlib) (2019.11.28)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests==2.18.4->csvwlib) (1.22)

Requirement already satisfied: slug in /anaconda3/lib/python3.7/site-packages (2.0)
Requirement already satisfied: goodtables in /anaconda3/lib/python3.7/site-packages (2.4.0)
Requirement already satisfied: datapackage>=1.10 in /anaconda3/lib/python3.7/site-packages (from goodtables) (1.10.0)
Requirement already satisfied: click>=6.6 in /anaconda3/lib/python3.7/site-packages (from goodtables) (7.0)
Requirement already satisfied: six>=1.9 in /anaconda3/lib/python3.7/site-packages (from goodtables) (1.12.0)
Requirement already satisfied: simpleeval>=0.9 in /anaconda3/lib/python3.7/site-packages (from goodtables) (0.9.8)
Requirement already satisfied: tabulator>=1.29 in /anaconda3/lib/python3.7/site-packages (from goodtables) (1.29.0)
Requirement already satisfied: tableschema>=1.10 in /anaconda3/lib/python3.7/site-packages (from goodtables) (1.10.0)
Requirement already satisfied: click-default-group in /anaconda3/lib/python3.7/site-packages (from goodtables) (1.2.2)
Requirement already satisfied: statistics>=1.0 in /anaconda3/lib/python3.7/site-packages (from goodtables) (1.0.3.5)
Requirement already satisfied: requests>=2.10 in /anaconda3/lib/python3.7/site-packages (from goodtables) (2.18.4)
Requirement already satisfied: jsonschema>=2.5 in /anaconda3/lib/python3.7/site-packages (from datapackage>=1.10->goodtables) (3.0.1)
Requirement already satisfied: cchardet>=1.0 in /anaconda3/lib/python3.7/site-packages (from datapackage>=1.10->goodtables) (2.1.4)
Requirement already satisfied: unicodecsv>=0.14 in /anaconda3/lib/python3.7/site-packages (from datapackage>=1.10->goodtables) (0.14.1)
Requirement already satisfied: jsonpointer>=1.10 in /anaconda3/lib/python3.7/site-packages (from datapackage>=1.10->goodtables) (2.0)
Requirement already satisfied: openpyxl>=2.6 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (2.6.2)
Requirement already satisfied: xlrd>=1.0 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (1.2.0)
Requirement already satisfied: jsonlines>=1.1 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (1.2.0)
Requirement already satisfied: sqlalchemy>=0.9.6 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (1.3.5)
Requirement already satisfied: ijson>=2.5 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (2.5.1)
Requirement already satisfied: boto3>=1.9 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (1.10.14)
Requirement already satisfied: linear-tsv>=1.0 in /anaconda3/lib/python3.7/site-packages (from tabulator>=1.29->goodtables) (1.1.0)
Requirement already satisfied: rfc3986>=1.1.0 in /anaconda3/lib/python3.7/site-packages (from tableschema>=1.10->goodtables) (1.3.2)
Requirement already satisfied: python-dateutil>=2.4 in /anaconda3/lib/python3.7/site-packages (from tableschema>=1.10->goodtables) (2.6.1)
Requirement already satisfied: isodate>=0.5.4 in /anaconda3/lib/python3.7/site-packages (from tableschema>=1.10->goodtables) (0.6.0)
Requirement already satisfied: docutils>=0.3 in /anaconda3/lib/python3.7/site-packages (from statistics>=1.0->goodtables) (0.14)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests>=2.10->goodtables) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests>=2.10->goodtables) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests>=2.10->goodtables) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests>=2.10->goodtables) (2019.11.28)
Requirement already satisfied: attrs>=17.4.0 in /anaconda3/lib/python3.7/site-packages (from jsonschema>=2.5->datapackage>=1.10->goodtables) (19.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /anaconda3/lib/python3.7/site-packages (from jsonschema>=2.5->datapackage>=1.10->goodtables) (0.14.11)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.7/site-packages (from jsonschema>=2.5->datapackage>=1.10->goodtables) (41.0.1)
Requirement already satisfied: et-xmlfile in /anaconda3/lib/python3.7/site-packages (from openpyxl>=2.6->tabulator>=1.29->goodtables) (1.0.1)
Requirement already satisfied: jdcal in /anaconda3/lib/python3.7/site-packages (from openpyxl>=2.6->tabulator>=1.29->goodtables) (1.4.1)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in /anaconda3/lib/python3.7/site-packages (from boto3>=1.9->tabulator>=1.29->goodtables) (0.2.1)
Requirement already satisfied: botocore<1.14.0,>=1.13.14 in /anaconda3/lib/python3.7/site-packages (from boto3>=1.9->tabulator>=1.29->goodtables) (1.13.14)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /anaconda3/lib/python3.7/site-packages (from boto3>=1.9->tabulator>=1.29->goodtables) (0.9.4)
Requirement already satisfied: PyGithub in /anaconda3/lib/python3.7/site-packages (1.46)
Requirement already satisfied: deprecated in /anaconda3/lib/python3.7/site-packages (from PyGithub) (1.2.7)
Requirement already satisfied: requests>=2.14.0 in /anaconda3/lib/python3.7/site-packages (from PyGithub) (2.18.4)
Requirement already satisfied: pyjwt in /anaconda3/lib/python3.7/site-packages (from PyGithub) (1.7.1)
Requirement already satisfied: wrapt<2,>=1.10 in /anaconda3/lib/python3.7/site-packages (from deprecated->PyGithub) (1.11.2)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub) (2019.11.28)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub) (2.6)

In [2]:
display(HTML('<h1 style="font-size:350%;text-align:center;font-family:impact;background-color:dodgerblue;"><i>Data Management Section:</i></h1>'))

### Stage Nulla: The Data Engineering Specification & Transform Notes:

***The specification should be in play before any transformation coding begins unless agreed with the wider team and decision makers!***

<img src="files/TransformDesign_HLE_Synthetic.png">

HELP ME LEIGH: We need to define the specification format / schema (it is possible we can later use this for automation). The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc.The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc. The above images are obviously synthetic, this cell and others would normally contain the specification etc.

### Stage I: Harvesting Human Readable Data Sources:
* **Using GSS_Utils we can web scrape data sources (such as .XLSX spreadsheets and other formats).**
* **Using the Scraper component of GSS-Utils we will display all the identified distributions of data at our defined landing page.**

In [3]:
# Amend the landing page string as required to locate your file distributions:

str_http_landing_page = 'https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/' \
                          'healthandlifeexpectancies/datasets/healthstatelifeexpectancyallagesuk'

scraper = Scraper(str_http_landing_page)
display(scraper)

## Health state life expectancy, all ages, UK

Pivot tables for health state life expectancy by sex and area type, divided by three-year intervals starting from 2009 to 2011.

### Description

Pivot tables for health state life expectancy by sex and area type, divided by two-year intervals starting from 2009 to 2011.

### Distributions

1. Health state life expectancy, all ages, UK ([MS Excel Spreadsheet](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/datasets/healthstatelifeexpectancyallagesuk/current/heestimates.xlsx)) - 2016-11-29
1. Health state life expectancy, all ages, UK ([application/zip](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/datasets/healthstatelifeexpectancyallagesuk/current/previous/v1/healthexpectanciespivottables.zip)) - 2016-11-29
1. Health state life expectancy, all ages, UK ([application/zip](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/datasets/healthstatelifeexpectancyallagesuk/current/previous/v2/healthexpectanciespivottablesversion2.zip)) - 2016-11-29
1. Health state life expectancy, all ages, UK ([MS Excel Spreadsheet](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/datasets/healthstatelifeexpectancyallagesuk/current/previous/v3/refpivottablesfinal.xlsx)) - 2016-11-29
1. Health state life expectancy, all ages, UK ([MS Excel Spreadsheet](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/datasets/healthstatelifeexpectancyallagesuk/current/previous/v4/hslepivotab1.xlsx)) - 2016-11-29

### Stage II: Identifying the Distribution to Extract and Process:
**For our demonstration we're selecting the first distribution (.xls) for processing...**

***Note:*** *our component scrapes associated meta data that we'll need later...*

In [4]:
# Using the list above we're selecting the first distribution: [0]. Each 'tab' will hold relevant Spreadsheet tabs
# from the encapsulated distribution - in out case all the tabs that are within a spreadsheet...

tabs = scraper.distributions[0].as_databaker()
distribution = scraper.distributions[0]
display(distribution)

In [5]:
display(HTML('<h1 style="font-size:350%;text-align:center;font-family:impact;background-color:deeppink;"><i>Data Engineering Section:</i></h1>'))

### Stage III: Data Wrangling:

**Purpose:** *Stage III is the section of the Notebook where your Pandas/Python skills come into play, this is where the scraped data (in our case an Excel Spreadsheet) will be transformed from human readable to machine readable format. We call this output transform 'tidy-data'.*

**Note:** *For the purposes of this Notebook we're only going to process two tabs of the spreadsheet. Where multiple tabs and multiple outputs are required and generated additional file / code management would obviously be necessary.*

**Transforms:** *Our tidy-data outputs are stored in a collection of Pandas DataFrames.*

**Validations:** *Validation of the transform will be achieved both manually by user and using a packaged component for basic checks; future tools and testing frameworks for COGS are expected to be developed in the near future.*

In [6]:
# Identify if execution of code is within a Notebook Environment:
boo_pythonNB_env = COGSTransformPack.boo_pythonNB_environment()

<span style='color:Grey'>***Execution Environment: ZMQInteractiveShell; setting boo_pythonNB_environment to: True.***</span>

In [7]:
# Get coding! This is where we code our data transforms. We currently have a requirement within the COGS team to
# produce a best practice and hints & tips guide. I personally prefer to data-wrangle using a Pandas dataframe over
# using DataBaker (M. Spooner).


str_tabsheetsinfocus = 'H' # Only process spreadsheet tabs beginning with this character.
if boo_pythonNB_env == True:
    COGSTransformPack.printmd("**Processing tabs that start with: " + str_tabsheetsinfocus + ".**")
    
i = 0 # Loop Variable.
ii = 0 # Loop Variable.
dataframe_collection = {} # Collection of Pandas DataFrames.


for tab in tabs:
    if tabs[i].name.startswith(str_tabsheetsinfocus):
        
        
        if tabs[i].name == 'HE - Country level estimates':
            ii = 1
            try:
                pd_tab = distribution.as_pandas(sheet_name = tabs[i].name) #, skiprows=1, header=None)
                pd_df_dimensions = pd_tab.iloc[:, :7] # This split is lost in our transformation - but it helped here.
                pd_df_observations = pd_tab.iloc[:, 7:14] # See above.
                pd_df_original = pd.concat([pd_df_dimensions, pd_df_observations], axis=1, sort=False)
                pd_df_transformed = pd_df_original.dropna(how='all')
                pd_df_transformed = pd_df_transformed.drop(columns=['Country', 'sex1', 'ageband'])
                pd_df_transformed['Period'] = pd_df_transformed['Period']\
                    .map(lambda x: f'gregorian-interval/{str(x)[:4]}-03-31T00:00:00/P3Y')
                pd_df_transformed.loc[pd_df_transformed['Sex'] == 'Males', 'Sex'] = 'M'
                pd_df_transformed.loc[pd_df_transformed['Sex'] == 'Females', 'Sex'] = 'F'
                pd_df_transformed['age group'][pd_df_transformed['age group'] == '<1'] = 'lessthan1'
                pd_df_transformed['age group'][pd_df_transformed['age group'] == '90+'] = '90plus'
                pd_df_transformed_le =\
                    pd_df_transformed[['Period', 'Code', 'Sex', 'age group', 'Life Expectancy (LE)_',\
                                       'LE Lower CI_', 'LE Upper CI_',\
                                       #'Proportion of Life Spent in "Good" Health (%)_']].copy()
                                      ]].copy()
                pd_df_transformed_hle =\
                    pd_df_transformed[['Period', 'Code', 'Sex', 'age group', 'Healthy Life Expectancy (HLE) _',\
                                       'HLE Lower CI_', 'HLE Upper CI_',\
                                       #'Proportion of Life Spent in "Good" Health (%)_']].copy()
                                       ]].copy()
                pd_df_transformed_le['TransformationType'] = 'LE'
                pd_df_transformed_hle['TransformationType'] = 'HLE'
                dataframe_collection[tabs[i].name + '_LE'] = pd_df_transformed_le
                dataframe_collection[tabs[i].name + '_HLE'] = pd_df_transformed_hle
                COGSTransformPack.printmd('[' + str(i) + '] Processed: ' + tabs[i].name + '.', colour='Green')
            except ERR_HECountryLevelEstimates:
                print('Error within ' + str(pd_df_name.append(tabs[i].name)) + ' process to extract to Pandas DF.')
            
            
        if tabs[i].name == 'HE - Region level estimates':
            ii = 1
            try:
                pd_tab = distribution.as_pandas(sheet_name = tabs[i].name)
                pd_df_dimensions = pd_tab.iloc[:, :8]
                pd_df_observations = pd_tab.iloc[:, 8:14]
                pd_df_original = pd.concat([pd_df_dimensions, pd_df_observations], axis=1, sort=False)
                pd_df_original.columns = pd_df_original.iloc[0]
                pd_df_original = pd_df_original[1:]
                pd_df_transformed = pd_df_original.dropna(how='all')
                pd_df_transformed = pd_df_transformed.drop(columns=['Area_name', 'sex1', 'ageband'])
                pd_df_transformed['Period'] = pd_df_transformed['Period']\
                    .map(lambda x: f'gregorian-interval/{str(x)[:4]}-03-31T00:00:00/P3Y')
                pd_df_transformed.loc[pd_df_transformed['Sex'] == 'Males', 'Sex'] = 'M'
                pd_df_transformed.loc[pd_df_transformed['Sex'] == 'Females', 'Sex'] = 'F'
                pd_df_transformed['Age group'][pd_df_transformed['Age group'] == '<1'] = 'lessthan1'
                pd_df_transformed['Age group'][pd_df_transformed['Age group'] == '90+'] = '90plus'
                pd_df_transformed_le =\
                    pd_df_transformed[['Period', 'Code', 'Sex', 'Age group', 'Life Expectancy (LE)_',\
                                       'LE Lower CI_', 'LE Upper CI_',\
                                       #'Proportion of Life Spent in "Good" Health (%)_']].copy()
                                       ]].copy()
                pd_df_transformed_hle =\
                    pd_df_transformed[['Period', 'Code', 'Sex', 'Age group', 'Healthy Life Expectancy (HLE) _',\
                                       'HLE Lower CI_', 'HLE Upper CI_',\
                                       #'Proportion of Life Spent in "Good" Health (%)_']].copy()
                                        ]].copy()
                pd_df_transformed_le['TransformationType'] = 'LE'
                pd_df_transformed_hle['TransformationType'] = 'HLE'
                dataframe_collection[tabs[i].name + '_LE'] = pd_df_transformed_le
                dataframe_collection[tabs[i].name + '_HLE'] = pd_df_transformed_hle
                COGSTransformPack.printmd('[' + str(i) + '] Processed: ' + tabs[i].name + '.', colour='Green')
            except ERR_HERegionLevelEstimates:
                print('Error within ' + str(pd_df_name.append(tabs[i].name)) + ' process to extract to Pandas DF.')            
    
        if ii == 0:
                COGSTransformPack.printmd('[' + str(i) + '] Ignoring: ' + tabs[i].name + '.', colour='Red')
        
    i += 1
    ii = 0 # Code should be amended to utilise loop break outs...

<span style='color:None'>**Processing tabs that start with: H.**</span>

<span style='color:Green'>[1] Processed: HE - Country level estimates.</span>

<span style='color:Green'>[2] Processed: HE - Region level estimates.</span>

<span style='color:Red'>[3] Ignoring: HE - MC,CA,WHB estimates.</span>

<span style='color:Red'>[4] Ignoring: HE - Local area estimates.</span>

### Stage IV (a): Data Wrangling Human Inspection:

**Purpose:** *This stage is intended so that the developer (you) can 'eye-ball' the 'tidy-data' transform.*

**Note:** *This is for human visualisation - not for specific testing (or as part of a testing framework).*

**Important:** *If the transformations appear correct we can proceed, otherwise we need to re-factor the data wrangling stage (Stage III).*

In [8]:
# Display your transform. Set the number of rows you'd like to display on screen. At present there's no functionality
# for random sampling or switching bewteen the head or tail of the data (possible future iteration(s)).
COGSTransformPack.display_DF_collection(dataframe_collection, 'Transform(s) for Inspection:', 5)

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Magenta'>**Transform(s) for Inspection:** </span>

<span style='color:Grey'>===================================================================================================================</span>

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_LE** *: First 5 records displayed of* 1600 records.</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,age group,Life Expectancy (LE)_,LE Lower CI_,LE Upper CI_,TransformationType
0,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,lessthan1,78.78073,78.75026,78.81120,LE
1,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,01-04,78.17075,78.14207,78.19942,LE
2,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,05-09,74.22782,74.19942,74.25623,LE
3,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,10-14,69.26178,69.23354,69.29002,LE
4,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,15-19,64.29632,64.26823,64.32440,LE

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_HLE** *: First 5 records displayed of* 1600 records.</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,age group,Healthy Life Expectancy (HLE) _,HLE Lower CI_,HLE Upper CI_,TransformationType
0,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,lessthan1,63.02647,62.87787,63.17508,HLE
1,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,01-04,62.37935,62.23008,62.52862,HLE
2,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,05-09,58.59795,58.44976,58.74614,HLE
3,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,10-14,53.86217,53.71597,54.00838,HLE
4,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,15-19,49.15668,49.01273,49.30062,HLE

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_LE** *: First 5 records displayed of* 2880 records.</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,Age group,Life Expectancy (LE)_,LE Lower CI_,LE Upper CI_,TransformationType
1,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,lessthan1,77.4021,77.2661,77.5382,LE
2,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,01-04,76.7237,76.5949,76.8526,LE
3,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,05-09,72.7749,72.6472,72.9026,LE
4,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,10-14,67.7985,67.6714,67.9256,LE
5,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,15-19,62.8475,62.7214,62.9737,LE

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_HLE** *: First 5 records displayed of* 2880 records.</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,Age group,Healthy Life Expectancy (HLE) _,HLE Lower CI_,HLE Upper CI_,TransformationType
1,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,lessthan1,59.7111,59.1905,60.2318,HLE
2,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,01-04,58.9645,58.4417,59.4873,HLE
3,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,05-09,55.0573,54.5354,55.5793,HLE
4,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,10-14,50.2258,49.7077,50.7439,HLE
5,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,15-19,45.5027,44.9906,46.0148,HLE

### Stage IV (c): Isolated Notebook Test(s):

**Purpose:** *Until a testing framework is designed and deployed testing of your 'tidy-data' is done manually.*

**Description:** *Tests can be programatically implemented using code / functions OR as implemented here via hardcoded values; it's up to you as an engineer until a framework arrives. Until the testing strategy is defined for our COGS development teams, checks that mirror those below are a good starting point; these include counts and sum'ing to ensure no data is lost during the transform process and random data entry point checks to ensure the data wrangling steps have not skewed the data schema / structure.*

*A testing framework should be implemented where tests are executed periodically to identify when new source data is available or has been revised - a test suite for a RAP (Re-producible Analytical Pipeline) can highlight failures and a requirment for a code-refactor.*

**Important:** *Remember that if testing values are hardcoded they will only apply to a specific data source; for example record counts may change between revisions of the same data source etc.*

**FOR INFORMATION! BE ADVISED - Intentionally one test here fails for demonstration purposes.**

In [9]:
# Okay then, it's up to you. Get testing!
# Note: Schema test would be hugely beneficial for RAPs.
# Hard-coded tests:
test_count_int = 0
test_count_successful = 0

test_count_int += 1 # Increment Test Counter...
if dataframe_collection['HE - Country level estimates_HLE'].shape[0] == 1600:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')

test_count_int += 1 # Increment Test Counter...
my_testdata = (dataframe_collection['HE - Country level estimates_HLE'].loc[(dataframe_collection['HE - Country level estimates_HLE']['Period'] == 'gregorian-interval/2009-03-31T00:00:00/P3Y') &
                 (dataframe_collection['HE - Country level estimates_HLE']['Code'] == 'E92000001') &
                 (dataframe_collection['HE - Country level estimates_HLE']['age group'] == 'lessthan1') &
                 (dataframe_collection['HE - Country level estimates_HLE']['Sex'] == 'M')]
                 )
my_expecteddata = pd.DataFrame({
                'Period': ['gregorian-interval/2009-03-31T00:00:00/P3Y'],
                'Code': ['E92000001'],
                'Sex': ['M'],
                'age group': ['lessthan1'],
                'Healthy Life Expectancy (HLE) _': [63.02647],
                'HLE Lower CI_': [62.87787],
                'HLE Upper CI_': [63.17508],
                #'Proportion of Life Spent in "Good" Health (%)_': [80.0024],
                'TransformationType': ['HLE']
                })
if my_testdata.equals(my_expecteddata):
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')

test_count_int += 1 # Increment Test Counter...
my_testdata = (dataframe_collection['HE - Country level estimates_HLE'].loc[(dataframe_collection['HE - Country level estimates_HLE']['Period'] == 'gregorian-interval/2016-03-31T00:00:00/P3Y') &
                 (dataframe_collection['HE - Country level estimates_HLE']['Code'] == 'W92000004') &
                 (dataframe_collection['HE - Country level estimates_HLE']['Sex'] == 'F') &
                 (dataframe_collection['HE - Country level estimates_HLE']['age group'] == '05-09')]
                ) 
my_testdata.index = np.arange(1,len(my_testdata)+1) # To avoid index comparison errors.
my_expecteddata = pd.DataFrame({
                'Period': ['gregorian-interval/2016-03-31T00:00:00/P3Y'],
                'Code': ['W92000004'],
                'Sex': ['F'],
                'age group': ['05-09'],
                'Healthy Life Expectancy (HLE) _': [57.56803],
                'HLE Lower CI_': [57.10483],
                'HLE Upper CI_': [58.03124],
                #'Proportion of Life Spent in "Good" Health (%)_': [74.21282],
                'TransformationType': ['HLE']
                })
my_expecteddata.index = np.arange(1,len(my_expecteddata)+1) # To avoid index comparison errors.
if my_testdata.equals(my_expecteddata):
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')

test_count_int += 1 # Increment Test Counter...
if dataframe_collection['HE - Country level estimates_LE']['Life Expectancy (LE)_'].sum() == 65114.214550000004:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')        

test_count_int += 1 # Increment Test Counter...
if dataframe_collection['HE - Region level estimates_HLE'].shape[0] == 2880:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')

test_count_int += 1 # Increment Test Counter...
if 1 == 2: # Intentional FAILED test for demo purposes...
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')        


test_count_int += 1 # Increment Test Counter...
if dataframe_collection['HE - Region level estimates_LE']['Life Expectancy (LE)_'].sum() == 118840.88113000023:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Successful.', colour='Green')
    test_count_successful += 1 # Increment Successful Test Counter...
else:
    COGSTransformPack.printmd('Test ID: [' + str(test_count_int) + '] Failed.', colour='Red')
                      
COGSTransformPack.printmd('**Test Rating: ' + str(round(test_count_successful/test_count_int*100,2)) + '% Successful.**', colour='Magenta')

<span style='color:Green'>Test ID: [1] Successful.</span>

<span style='color:Green'>Test ID: [2] Successful.</span>

<span style='color:Green'>Test ID: [3] Successful.</span>

<span style='color:Green'>Test ID: [4] Successful.</span>

<span style='color:Green'>Test ID: [5] Successful.</span>

<span style='color:Red'>Test ID: [6] Failed.</span>

<span style='color:Green'>Test ID: [7] Successful.</span>

<span style='color:Magenta'>**Test Rating: 85.71% Successful.**</span>

### Stage IV (?): Isolated Notebook Test(s) - Useful Tip:

**Did you know?:** *Having trouble using Python 'assert' or Panda's Dataframe equality checks? A lot of the time, it's the schema that doesn't 'match' even though the data entries appear to be the same.*

***Try the following '.info(verbose=True) code-snippet to investigate schemas:***

In [10]:
# Example of a schema - usually an assert will fail where two schemas do not match i.e. float32 to float64 will
# fail even if the data entries match.
my_expecteddata.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1 entries, 1 to 1
Data columns (total 8 columns):
Period                             1 non-null object
Code                               1 non-null object
Sex                                1 non-null object
age group                          1 non-null object
Healthy Life Expectancy (HLE) _    1 non-null float64
HLE Lower CI_                      1 non-null float64
HLE Upper CI_                      1 non-null float64
TransformationType                 1 non-null object
dtypes: float64(3), object(5)
memory usage: 72.0+ bytes

### Stage V (a): Creating & Mapping Reference Data and Data Markers - Identifying the Data Elements:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *We must isolate the dimensions (keys) from the observations (values) by...*

* *Generating the components from the transforms;*
* *Strip out data elements - remove all dimensions to leave only the observations thus providing our codelist keys.*

In [11]:
# Get list of columns / collection of component elements that will be used to define the codelists.
codelist_cols = []
dataframe_elements_collection = {}

codelist_cols = COGSTransformPack.get_component_elements(dataframe_collection)
dataframe_elements_collection = COGSTransformPack.get_transform_component_schema(dataframe_collection, codelist_cols)

COGSTransformPack.display_DF_collection(dataframe_elements_collection, 'Initial Component DataFrames:')

<span style='color:Green'>**Extracted columns from dataset HE - Country level estimates_LE:**</span>

<span style='color:Grey'>['Period', 'Code', 'Sex', 'age group', 'Life Expectancy (LE)_', 'LE Lower CI_', 'LE Upper CI_', 'TransformationType']</span>

<span style='color:Green'>**Extracted columns from dataset HE - Country level estimates_HLE:**</span>

<span style='color:Grey'>['Period', 'Code', 'Sex', 'age group', 'Healthy Life Expectancy (HLE) _', 'HLE Lower CI_', 'HLE Upper CI_', 'TransformationType']</span>

<span style='color:Green'>**Extracted columns from dataset HE - Region level estimates_LE:**</span>

<span style='color:Grey'>['Period', 'Code', 'Sex', 'Age group', 'Life Expectancy (LE)_', 'LE Lower CI_', 'LE Upper CI_', 'TransformationType']</span>

<span style='color:Green'>**Extracted columns from dataset HE - Region level estimates_HLE:**</span>

<span style='color:Grey'>['Period', 'Code', 'Sex', 'Age group', 'Healthy Life Expectancy (HLE) _', 'HLE Lower CI_', 'HLE Upper CI_', 'TransformationType']</span>

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Magenta'>**Initial Component DataFrames:** </span>

<span style='color:Grey'>===================================================================================================================</span>

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_LE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

  HE - Country level estimates_LE Entry Type
0                          Period  Dimension
1                            Code  Dimension
2                             Sex  Dimension
3                       age group  Dimension
4           Life Expectancy (LE)_  Dimension
5                    LE Lower CI_  Dimension
6                    LE Upper CI_  Dimension
7              TransformationType  Dimension

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_HLE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

  HE - Country level estimates_HLE Entry Type
0                           Period  Dimension
1                             Code  Dimension
2                              Sex  Dimension
3                        age group  Dimension
4  Healthy Life Expectancy (HLE) _  Dimension
5                    HLE Lower CI_  Dimension
6                    HLE Upper CI_  Dimension
7               TransformationType  Dimension

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_LE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

  HE - Region level estimates_LE Entry Type
0                         Period  Dimension
1                           Code  Dimension
2                            Sex  Dimension
3                      Age group  Dimension
4          Life Expectancy (LE)_  Dimension
5                   LE Lower CI_  Dimension
6                   LE Upper CI_  Dimension
7             TransformationType  Dimension

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_HLE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

   HE - Region level estimates_HLE Entry Type
0                           Period  Dimension
1                             Code  Dimension
2                              Sex  Dimension
3                        Age group  Dimension
4  Healthy Life Expectancy (HLE) _  Dimension
5                    HLE Lower CI_  Dimension
6                    HLE Upper CI_  Dimension
7               TransformationType  Dimension

### Stage V (b): Creating & Mapping Reference Data and Data Markers - Assign the Data Elements:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *We must manually assign the element type:*

* *By default the element type is set to 'Dimension';*
* *Define the observations in the data item catalogues by...:*
* *using the assign_transform_component_type() component in the following code cells manually code the appropriate element types ('Dimension', 'Observation' or 'Measure').*

In [12]:
# Currently does not support assignment of different types where the same element name is present in multiple
# catalogue items but you require different types!
# Note code here is in-efficient due to multiple passes of the collection in the function per line below:
COGSTransformPack.assign_transform_component_type(dataframe_elements_collection, 'Life Expectancy (LE)_', 'Measure')
COGSTransformPack.assign_transform_component_type(dataframe_elements_collection, 'LE Lower CI_', 'Observation')
COGSTransformPack.assign_transform_component_type(dataframe_elements_collection, 'LE Upper CI_', 'O')
COGSTransformPack.assign_transform_component_type(dataframe_elements_collection, 'Healthy Life Expectancy (HLE) _', 'M')
COGSTransformPack.assign_transform_component_type(dataframe_elements_collection, 'HLE Lower CI_', 'o')
COGSTransformPack.assign_transform_component_type(dataframe_elements_collection, 'HLE Upper CI_', 'o')

# Display your assignments:
str_display_revised = ('Revised Component DataFrames: <br>WARNING!:** Please be AWARE that you should not proceed until the data items are correctly assigned as being either a Dimension or an Observation. <br>If the results below show errors please fix by re-factoring your code and re-run**!')
COGSTransformPack.display_DF_collection(dataframe_elements_collection, str_display_revised)

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Magenta'>**Revised Component DataFrames: <br>WARNING!:** Please be AWARE that you should not proceed until the data items are correctly assigned as being either a Dimension or an Observation. <br>If the results below show errors please fix by re-factoring your code and re-run**!** </span>

<span style='color:Grey'>===================================================================================================================</span>

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_LE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

  HE - Country level estimates_LE   Entry Type
0                          Period    Dimension
1                            Code    Dimension
2                             Sex    Dimension
3                       age group    Dimension
4           Life Expectancy (LE)_      Measure
5                    LE Lower CI_  Observation
6                    LE Upper CI_  Observation
7              TransformationType    Dimension

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_HLE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

  HE - Country level estimates_HLE   Entry Type
0                           Period    Dimension
1                             Code    Dimension
2                              Sex    Dimension
3                        age group    Dimension
4  Healthy Life Expectancy (HLE) _      Measure
5                    HLE Lower CI_  Observation
6                    HLE Upper CI_  Observation
7               TransformationType    Dimension

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_LE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

  HE - Region level estimates_LE   Entry Type
0                         Period    Dimension
1                           Code    Dimension
2                            Sex    Dimension
3                      Age group    Dimension
4          Life Expectancy (LE)_      Measure
5                   LE Lower CI_  Observation
6                   LE Upper CI_  Observation
7             TransformationType    Dimension

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_HLE** *: All 8 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

   HE - Region level estimates_HLE   Entry Type
0                           Period    Dimension
1                             Code    Dimension
2                              Sex    Dimension
3                        Age group    Dimension
4  Healthy Life Expectancy (HLE) _      Measure
5                    HLE Lower CI_  Observation
6                    HLE Upper CI_  Observation
7               TransformationType    Dimension

### Stage V (c): Creating & Mapping Reference Data and Data Markers - Generating Codelists:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *Function generated code-lists:*

* *Codelists are created from the Dimension elements as assigned.*

In [13]:
# Codelist generation via component - get_codelists_from_dimensions():
dataframe_codelists_collection = {}
dataframe_codelists_collection = COGSTransformPack.get_codelists_from_dimensions(dataframe_collection, dataframe_elements_collection)

# Display your Codelists:
COGSTransformPack.display_DF_collection(dataframe_codelists_collection, 'Codelists (Generated from get_codelists_from_dimensions()):', 20)

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Magenta'>**Codelists (Generated from get_codelists_from_dimensions()):** </span>

<span style='color:Grey'>===================================================================================================================</span>

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_LE** *: All 20 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,age group,TransformationType
0,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,lessthan1,LE
1,gregorian-interval/2010-03-31T00:00:00/P3Y,K02000001,F,01-04,NaN
2,gregorian-interval/2011-03-31T00:00:00/P3Y,N92000002,NaN,05-09,NaN
3,gregorian-interval/2012-03-31T00:00:00/P3Y,S92000003,NaN,10-14,NaN
4,gregorian-interval/2013-03-31T00:00:00/P3Y,W92000004,NaN,15-19,NaN
5,gregorian-interval/2014-03-31T00:00:00/P3Y,NaN,NaN,20-24,NaN
6,gregorian-interval/2015-03-31T00:00:00/P3Y,NaN,NaN,25-29,NaN
7,gregorian-interval/2016-03-31T00:00:00/P3Y,NaN,NaN,30-34,NaN
8,NaN,NaN,NaN,35-39,NaN
9,NaN,NaN,NaN,40-44,NaN
10,NaN,NaN,NaN,45-49,NaN
11,NaN,NaN,NaN,50-54,NaN
12,NaN,NaN,NaN,55-59,NaN
13,NaN,NaN,NaN,60-64,NaN
14,NaN,NaN,NaN,65-69,NaN
15,NaN,NaN,NaN,70-74,NaN
16,NaN,NaN,NaN,75-79,NaN
17,NaN,NaN,NaN,80-84,NaN
18,NaN,NaN,NaN,85-89,NaN
19,NaN,NaN,NaN,90plus,NaN

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Country level estimates_HLE** *: All 20 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,age group,TransformationType
0,gregorian-interval/2009-03-31T00:00:00/P3Y,E92000001,M,lessthan1,HLE
1,gregorian-interval/2010-03-31T00:00:00/P3Y,K02000001,F,01-04,NaN
2,gregorian-interval/2011-03-31T00:00:00/P3Y,N92000002,NaN,05-09,NaN
3,gregorian-interval/2012-03-31T00:00:00/P3Y,S92000003,NaN,10-14,NaN
4,gregorian-interval/2013-03-31T00:00:00/P3Y,W92000004,NaN,15-19,NaN
5,gregorian-interval/2014-03-31T00:00:00/P3Y,NaN,NaN,20-24,NaN
6,gregorian-interval/2015-03-31T00:00:00/P3Y,NaN,NaN,25-29,NaN
7,gregorian-interval/2016-03-31T00:00:00/P3Y,NaN,NaN,30-34,NaN
8,NaN,NaN,NaN,35-39,NaN
9,NaN,NaN,NaN,40-44,NaN
10,NaN,NaN,NaN,45-49,NaN
11,NaN,NaN,NaN,50-54,NaN
12,NaN,NaN,NaN,55-59,NaN
13,NaN,NaN,NaN,60-64,NaN
14,NaN,NaN,NaN,65-69,NaN
15,NaN,NaN,NaN,70-74,NaN
16,NaN,NaN,NaN,75-79,NaN
17,NaN,NaN,NaN,80-84,NaN
18,NaN,NaN,NaN,85-89,NaN
19,NaN,NaN,NaN,90plus,NaN

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_LE** *: All 20 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,Age group,TransformationType
0,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,lessthan1,LE
1,gregorian-interval/2010-03-31T00:00:00/P3Y,E12000002,F,01-04,NaN
2,gregorian-interval/2011-03-31T00:00:00/P3Y,E12000003,NaN,05-09,NaN
3,gregorian-interval/2012-03-31T00:00:00/P3Y,E12000004,NaN,10-14,NaN
4,gregorian-interval/2013-03-31T00:00:00/P3Y,E12000005,NaN,15-19,NaN
5,gregorian-interval/2014-03-31T00:00:00/P3Y,E12000006,NaN,20-24,NaN
6,gregorian-interval/2015-03-31T00:00:00/P3Y,E12000007,NaN,25-29,NaN
7,gregorian-interval/2016-03-31T00:00:00/P3Y,E12000008,NaN,30-34,NaN
8,NaN,E12000009,NaN,35-39,NaN
9,NaN,NaN,NaN,40-44,NaN
10,NaN,NaN,NaN,45-49,NaN
11,NaN,NaN,NaN,50-54,NaN
12,NaN,NaN,NaN,55-59,NaN
13,NaN,NaN,NaN,60-64,NaN
14,NaN,NaN,NaN,65-69,NaN
15,NaN,NaN,NaN,70-74,NaN
16,NaN,NaN,NaN,75-79,NaN
17,NaN,NaN,NaN,80-84,NaN
18,NaN,NaN,NaN,85-89,NaN
19,NaN,NaN,NaN,90plus,NaN

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Blue'>**HE - Region level estimates_HLE** *: All 20 records displayed.*</span>

<span style='color:Grey'>===================================================================================================================</span>

,Period,Code,Sex,Age group,TransformationType
0,gregorian-interval/2009-03-31T00:00:00/P3Y,E12000001,M,lessthan1,HLE
1,gregorian-interval/2010-03-31T00:00:00/P3Y,E12000002,F,01-04,NaN
2,gregorian-interval/2011-03-31T00:00:00/P3Y,E12000003,NaN,05-09,NaN
3,gregorian-interval/2012-03-31T00:00:00/P3Y,E12000004,NaN,10-14,NaN
4,gregorian-interval/2013-03-31T00:00:00/P3Y,E12000005,NaN,15-19,NaN
5,gregorian-interval/2014-03-31T00:00:00/P3Y,E12000006,NaN,20-24,NaN
6,gregorian-interval/2015-03-31T00:00:00/P3Y,E12000007,NaN,25-29,NaN
7,gregorian-interval/2016-03-31T00:00:00/P3Y,E12000008,NaN,30-34,NaN
8,NaN,E12000009,NaN,35-39,NaN
9,NaN,NaN,NaN,40-44,NaN
10,NaN,NaN,NaN,45-49,NaN
11,NaN,NaN,NaN,50-54,NaN
12,NaN,NaN,NaN,55-59,NaN
13,NaN,NaN,NaN,60-64,NaN
14,NaN,NaN,NaN,65-69,NaN
15,NaN,NaN,NaN,70-74,NaN
16,NaN,NaN,NaN,75-79,NaN
17,NaN,NaN,NaN,80-84,NaN
18,NaN,NaN,NaN,85-89,NaN
19,NaN,NaN,NaN,90plus,NaN

In [14]:
display(HTML('<h1 style="font-size:350%;text-align:center;font-family:impact;background-color:dodgerblue;"><i>Data Management Section:</i></h1>'))

### Stage VI (a): Mapping our Transforms with our Reference Data - Reference Data Load:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *We must map / associate our transformed data dimensions with our reference data repository / master database:*
* Load to memory our master reference data.
* Map / associate reference data with our transformed data entities / dimensions.
    * *Note an automated attempt to map is conducted - but manual intervention is likely.*
    * *Mapping between the transformed dimensions (components) and the master reference data is completed manually where the automation routine fails.*

In [15]:
# Specify the source of the reference data master (currently COGS has a split-by-data-family configuration):
url_ref_repo_components = "https://raw.githubusercontent.com/GSS-Cogs/family-disability/master/reference/components.csv"
url_ref_repo_columns = "https://raw.githubusercontent.com/GSS-Cogs/family-disability/master/reference/columns.csv"

df_ref_repo_columns = pd.read_csv(url_ref_repo_columns)
COGSTransformPack.printmd('**Displaying: ' + url_ref_repo_columns + ':**')
display(df_ref_repo_columns)

df_ref_repo_components = pd.read_csv(url_ref_repo_components)
COGSTransformPack.printmd('**Displaying: ' + url_ref_repo_components + ':**')
display(df_ref_repo_components)

<span style='color:None'>**Displaying: https://raw.githubusercontent.com/GSS-Cogs/family-disability/master/reference/columns.csv:**</span>

,title,name,component_attachment,property_template,value_template,datatype,value_transformation,regex,range
0,Measure Type,measure_type,qb:dimension,http://purl.org/linked-data/cube#measureType,http://gss-data.org.uk/def/measure/{measure_type},string,slugize,NaN,qb:MeasureProperty
1,Area,area,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://statistics.data.gov.uk/id/statistical-g...,string,NaN,NaN,NaN
2,Sex,sex,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://purl.org/linked-data/sdmx/2009/code#sex...,string,NaN,^(M|F|T|U|N)$,http://purl.org/linked-data/sdmx/2009/code#Sex
3,Household Disability Status,household_disability_status,qb:dimension,http://gss-data.org.uk/def/dimension/household...,http://gss-data.org.uk/def/concept/household-d...,string,slugize,NaN,http://gss-data.org.uk/def/classes/household-d...
4,Workless Household Type,workless_household_type,qb:dimension,http://gss-data.org.uk/def/dimension/workless-...,http://gss-data.org.uk/def/concept/workless-ho...,string,slugize,NaN,http://gss-data.org.uk/def/classes/workless-ho...
5,Unit,unit,qb:attribute,http://purl.org/linked-data/sdmx/2009/attribut...,http://gss-data.org.uk/def/concept/measurement...,string,unitize,NaN,NaN
6,Sample Size,sample_size,qb:attribute,http://gss-data.org.uk/def/attribute/sample-size,NaN,number,NaN,NaN,NaN
7,Lower CI,lower_ci,qb:attribute,http://gss-data.org.uk/def/attribute/lower-ci,NaN,number,NaN,NaN,NaN
8,Upper CI,upper_ci,qb:attribute,http://gss-data.org.uk/def/attribute/upper-ci,NaN,number,NaN,NaN,NaN
9,Value,value,NaN,http://gss-data.org.uk/def/measure/{measure_type},NaN,number,NaN,NaN,NaN
10,Severity,severity,qb:dimension,http://gss-data.org.uk/def/dimension/severity,http://gss-data.org.uk/def/concept/severity/{s...,string,slugize,NaN,NaN
11,Hours per Week,hours_per_week,qb:dimension,http://gss-data.org.uk/def/dimension/hours-per...,http://gss-data.org.uk/def/concept/hours-per-w...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
12,FRS Units,frs_units,qb:dimension,http://gss-data.org.uk/def/dimension/frs-units,http://gss-data.org.uk/def/concept/frs-units/{...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
13,Employment Status,employment_status,qb:dimension,http://gss-data.org.uk/def/dimension/employmen...,http://gss-data.org.uk/def/concept/employment-...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
14,Employment Type,employment_type,qb:dimension,http://gss-data.org.uk/def/dimension/employmen...,http://gss-data.org.uk/def/concept/employment-...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
15,Adult Carer,adult_carer,qb:dimension,http://gss-data.org.uk/def/dimension/adult-carer,http://gss-data.org.uk/def/concept/adult-carer...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
16,Source of Income,source_of_income,qb:dimension,http://gss-data.org.uk/def/dimension/source-of...,http://gss-data.org.uk/def/concept/source-of-i...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
17,Net Weekly Income,net_weekly_income,qb:dimension,http://gss-data.org.uk/def/dimension/net-weekl...,http://gss-data.org.uk/def/concept/net-weekly-...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
18,Person cared for Type,person_cared_for_type,qb:dimension,http://gss-data.org.uk/def/dimension/person-ca...,http://gss-data.org.uk/def/concept/person-care...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
19,Person cared for,person_cared_for,qb:dimension,http://gss-data.org.uk/def/dimension/person-ca...,http://gss-data.org.uk/def/concept/person-care...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
20,Frequency of care,frequency_of_care,qb:dimension,http://gss-data.org.uk/def/dimension/frequency...,http://gss-data.org.uk/def/concept/frequency-o...,string,slugize,NaN,http://gss-data.org.uk/def/classes/gp-practice...
21,NHS Geography,nhs_geography,qb:dimension,http://gss-data.org.uk/def/dimension/nhs-geogr...,http://gss-data.org.uk/def/concept/nhs-geograp...,string,NaN,NaN,http://gss-data.org.uk/def/classes/gp-practice...
22,ONS Geography,ons_geography,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://statistics.data.gov.uk/id/statistical-g...,string,NaN,[A-Z][0-9]{8},NaN
23,Disability,disability,qb:dimension,http://gss-data.org.uk/def/dimension/disability,http://gss-data.org.uk/def/concept/disability/...,string,NaN,NaN,http://gss-data.org.uk/def/classes/disability/...
24,Period,period,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://reference.data.gov.uk/id/{+period},string,NaN,^(year/[0-9]{4}|gregorian-interval/.*|month/[0...,http://reference.data.gov.uk/def/intervals/Int...
25,FRS Age Group,frs_age_group,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://gss-data.org.uk/def/concept/dwp-frs-age...,string,NaN,NaN,http://gss-data.org.uk/def/classes/dwp-frs-age...
26,Marker,marker,qb:attribute,http://purl.org/linked-data/sdmx/2009/attribut...,http://gss-data.org.uk/def/concept/markers/{ma...,string,NaN,NaN,NaN
27,Reasons for failing to maintain accommodation,reasons_for_failing_to_maintain_accommodation,qb:dimension,http://gss-data.org.uk/def/dimension/reasons-f...,http://gss-data.org.uk/def/concept/reasons-for...,string,NaN,NaN,http://gss-data.org.uk/def/classes/homelessnes...
28,Identified support needs of homeless households,identified_support_needs_of_homeless_households,qb:dimension,http://gss-data.org.uk/def/dimension/identifie...,http://gss-data.org.uk/def/concept/identified-...,string,NaN,NaN,http://gss-data.org.uk/def/classes/homelessnes...
29,Reasons for homelessness application,reasons_for_homelessness_application,qb:dimension,http://gss-data.org.uk/def/dimension/reasons-f...,http://gss-data.org.uk/def/concept/reasons-for...,string,NaN,NaN,http://gss-data.org.uk/def/classes/homelessnes...
...,...,...,...,...,...,...,...,...,...
101,Reporting Period,period,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://reference.data.gov.uk/id/{+period},string,NaN,^(year/[0-9]{4}|gregorian-interval/.*|month/[0...,http://reference.data.gov.uk/def/intervals/Int...
102,Breakdown,breakdown,qb:dimension,http://gss-data.org.uk/def/dimension/breakdown,http://gss-data.org.uk/def/concept/breakdown/{...,string,slugize,NaN,http://gss-data.org.uk/def/classes/breakdown/b...
103,CCG Indicator,ccg_indicator,qb:dimension,http://gss-data.org.uk/def/dimension/ccg-indic...,http://gss-data.org.uk/def/concept/ccg-indicat...,string,slugize,NaN,http://gss-data.org.uk/def/classes/ccg-indicat...
104,NHS Level,nhs_level,qb:dimension,http://gss-data.org.uk/def/dimension/nhs-level,http://gss-data.org.uk/def/concept/nhs-level/{...,string,slugize,NaN,http://gss-data.org.uk/def/classes/nhs-level/n...
105,Markers,markers,qb:attribute,http://purl.org/linked-data/sdmx/2009/attribut...,http://gss-data.org.uk/def/concept/markers/{ma...,string,slugize,NaN,NaN
106,Disability Status,disability_status,qb:dimension,http://gss-data.org.uk/def/dimension/disabilit...,http://gss-data.org.uk/def/concept/disability-...,string,slugize,NaN,http://gss-data.org.uk/def/classes/disability-...
107,Responsibility Level,responsibility_level,qb:dimension,http://gss-data.org.uk/def/dimension/responsib...,http://gss-data.org.uk/def/concept/responsibil...,string,slugize,NaN,http://gss-data.org.uk/def/classes/responsibil...
108,Department,department,qb:dimension,http://gss-data.org.uk/def/dimension/department,http://gss-data.org.uk/def/concept/department/...,string,slugize,NaN,http://gss-data.org.uk/def/classes/department/...
109,Salary Band,salary_band,qb:dimension,http://gss-data.org.uk/def/dimension/salary-band,http://gss-data.org.uk/def/concept/salary-band...,string,slugize,NaN,http://gss-data.org.uk/def/classes/salary-band...
110,Profession of Post,profession_of_post,qb:dimension,http://gss-data.org.uk/def/dimension/professio...,http://gss-data.org.uk/def/concept/profession-...,string,slugize,NaN,http://gss-data.org.uk/def/classes/profession-...
111,Nationality,nationality,qb:dimension,http://gss-data.org.uk/def/dimension/nationality,http://gss-data.org.uk/def/concept/nationality...,string,slugize,NaN,http://gss-data.org.uk/def/classes/nationality...
112,Ethnicity,ethnicity,qb:dimension,http://gss-data.org.uk/def/dimension/ethnicity,http://gss-data.org.uk/def/concept/ethnicity/{...,string,slugize,NaN,http://gss-data.org.uk/def/classes/ethnicity/e...
113,Entrants or Leavers,entrants_or_leavers,qb:dimension,http://gss-data.org.uk/def/dimension/entrants-...,http://gss-data.org.uk/def/concept/entrants-or...,string,slugize,NaN,http://gss-data.org.uk/def/classes/entrants-or...
114,Type of Employment,type_of_employment,qb:dimension,http://gss-data.org.uk/def/dimension/type-of-e...,http://gss-data.org.uk/def/concept/type-of-emp...,string,slugize,NaN,http://gss-data.org.uk/def/classes/type-of-emp...
115,Status of Employment,status_of_employment,qb:dimension,http://gss-data.org.uk/def/dimension/status-of...,http://gss-data.org.uk/def/concept/status-of-e...,string,slugize,NaN,http://gss-data.org.uk/def/classes/status-of-e...
116,NUTS Region name,nuts_region_name,qb:dimension,http://gss-data.org.uk/def/dimension/nuts-regi...,http://gss-data.org.uk/def/concept/nuts-region...,string,slugize,NaN,http://gss-data.org.uk/def/classes/nuts-region...
117,NUTS Area Code,nuts_area_code,qb:dimension,http://gss-data.org.uk/def/dimension/nuts-area...,http://gss-data.org.uk/def/concept/nuts-area-c...,string,slugize,NaN,http://gss-data.org.uk/def/classes/nuts-area-c...
118,Life Expectancy Estimate Type,life_expectancy_estimate_type,qb:dimension,http://gss-data.org.uk/def/dimension/life-expe...,http://gss-data.org.uk/def/concept/life-expect...,string,slugize,NaN,http://gss-data.org.uk/def/classes/life-expect...
119,Headcount,headcount,qb:measure,http://gss-data.org.uk/def/measure/headcount,NaN,number,NaN,NaN,NaN
120,All Employees,all_employees,qb:measure,http://gss-data.org.uk/def/measure/all-employees,NaN,number,NaN,NaN,NaN
121,Median gender pay gap in percent,median_gender_pay_gap_in_percent,qb:measure,http://gss-data.org.uk/def/measure/median-gend...,NaN,number,NaN,NaN,NaN
122,Mean Earnings,mean_earnings,qb:measure,http://gss-data.org.uk/def/measure/mean-earnings,NaN,number,NaN,NaN,NaN
123,Median Earnings,median_earnings,qb:measure,http://gss-data.org.uk/def/measure/median-earn...,NaN,number,NaN,NaN,NaN
124,Percentage of each Gender by department,percentage_of_each_gender_by_department,qb:measure,http://gss-data.org.uk/def/measure/percentage-...,NaN,number,NaN,NaN,NaN
125,DfE Geography,dfe_geography,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimensio...,http://statistics.data.gov.uk/id/statistical-g...,string,NaN,[A-Z][0-9]{8},NaN
126,DfE Statements of SEN or EHC Plan Description,dfe_statements_of_sen_or_ehc_plan_description,qb:dimension,http://gss-data.org.uk/def/dimension/dfe-state...,http://gss-data.org.uk/def/concept/dfe-stateme...,string,slugize,NaN,http://gss-data.org.uk/def/classes/dfe-stateme...
127,DfE Statements or EHC Plan Type,dfe_statements_or_ehc_plan_type,qb:dimension,http://gss-data.org.uk/def/dimension/dfe-state...,http://gss-data.org.uk/def/concept/dfe-stateme...,string,slugize,NaN,http://gss-data.org.uk/def/classes/dfe-stateme...
128,DfE Statements of SEN or EHC Plan Provider,dfe_statements_of_sen_or_ehc_plan_provider,qb:dimension,http://gss-data.org.uk/def/dimension/dfe-state...,http://gss-data.org.uk/def/concept/dfe-stateme...,string,slugize,NaN,http://gss-data.org.uk/def/classes/dfe-stateme...
129,DfE Marker,dfe_marker,qb:dimension,http://gss-data.org.uk/def/dimension/dfe-marker,http://gss-data.org.uk/def/concept/dfe-marker/...,string,slugize,NaN,http://gss-data.org.uk/def/classes/dfe-marker/...
130,ONS Marker,ons_marker,qb:attribute,http://purl.org/linked-data/sdmx/2009/attribut...,http://gss-data.org.uk/def/concept/ons-marker/...,string,NaN,NaN,NaN

<span style='color:None'>**Displaying: https://raw.githubusercontent.com/GSS-Cogs/family-disability/master/reference/components.csv:**</span>

,Label,Description,Component Type,Codelist
0,Household Disability Status,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/hous...
1,Workless Household Type,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/work...
2,Percentage of People,The percentage of all people measured who meet...,Measure,NaN
3,Identified support needs of homeless households,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/iden...
4,Reasons for failing to maintain accommodation,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/reas...
5,Reasons for homelessness application,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/reas...
6,Trend,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/trend
7,Standard Population,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/phe-...
8,County & UA (pre Apr2019) deprivation deciles ...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/coun...
9,District & UA (pre Apr2019) deprivation decil...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dist...
10,County & UA deprivation deciles in England (IM...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/coun...
11,District & UA deprivation deciles in England (...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dist...
12,County & UA deprivation deciles in England (IM...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/coun...
13,District & UA deprivation deciles in England (...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dist...
14,County & UA deprivation deciles in England (IM...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/coun...
15,District & UA deprivation deciles in England (...,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dist...
16,Ethnic groups,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/ethn...
17,LSOA11 deprivation deciles in England (IMD2015),NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/lsoa...
18,Socioeconomic group (18-64 yrs),NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/soci...
19,Religion - 8 categories,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/reli...
20,Country of birth,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/coun...
21,Health status,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/heal...
22,Sexuality - 5 categories,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/sexu...
23,Percentage,Percentage,Measure,NaN
24,FRS Units,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/frs-...
25,Crude rate,NaN,Measure,NaN
26,Score,NaN,Measure,NaN
27,Directly standardised rate,NaN,Measure,NaN
28,Indirectly standardised rate,NaN,Measure,NaN
29,Indirectly standardised ratio,NaN,Measure,NaN
...,...,...,...,...
65,Breakdown,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/brea...
66,CCG Indicator,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/ccg-...
67,NHS Level,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/nhs-...
68,Markers,NaN,Attribute,http://gss-data.org.uk/def/concept-scheme/markers
69,Standardised admission rate,NaN,Measure,NaN
70,Standardised ratio,NaN,Measure,NaN
71,Standardised emergency admission rate,NaN,Measure,NaN
72,Ethnicity,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/ethn...
73,Disability Status,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/disa...
74,Nationality,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/nati...
75,Salary Band,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/sala...
76,Department,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/Depa...
77,Profession of Post,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/prof...
78,Type of Employment,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/type...
79,Status of Employment,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/stat...
80,Entrants or Leavers,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/entr...
81,Responsibility Level,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/resp...
82,NUTS Region name,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/nuts...
83,NUTS Area Code,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/nuts...
84,Life Expectancy Estimate Type,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/life...
85,Headcount,NaN,Measure,NaN
86,Median gender pay gap in percent,NaN,Measure,NaN
87,Mean Earnings,NaN,Measure,NaN
88,Median Earnings,NaN,Measure,NaN
89,Percentage of each Gender by department,NaN,Measure,NaN
90,All Employees,NaN,Measure,NaN
91,DfE Statements of SEN or EHC Plan Description,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dfe-...
92,DfE Statements or EHC Plan Type,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dfe-...
93,DfE Statements of SEN or EHC Plan Provider,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dfe-...
94,DfE Marker,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/dfe-...

### Stage VI (b): Mapping our Transforms with our Reference Data - Reference / Transform Automated Map:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *We must map / associate our transformed data dimensions with our reference data repository / master database:*
* Load to memory our master reference data.
* Map / associate reference data with our transformed data entities / dimensions.
    * *Note an automated attempt to map is conducted - but manual intervention is likely.*
    * *Mapping between the transformed dimensions (components) and the master reference data is completed manually where the automation routine fails.*

In [ ]:
# Automated mapping of transformed components with the master reference data:
dataframe_mapped_elements_collection = {}
dataframe_mapped_elements_collection_errors = {}

#dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors =\
#    COGSTransformPack.map_REFData_with_Transform(dataframe_elements_collection,\
#                                                 df_ref_repo_columns, df_ref_repo_components)

print('match on name first or codelist? Need a debug mode on this one? Include matched columns too?')

dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors =\
    xxmap_REFData_with_Transform(dataframe_elements_collection,\
                                                 df_ref_repo_columns, df_ref_repo_components, dataframe_codelists_collection, execute_flag = 'AutoMap', automap_threshold = 50)

COGSTransformPack.display_DF_collection(dataframe_mapped_elements_collection, 'These are the components that automatically matched:** <br>Please use caution before proceeding - these automated matches may be incorrect**!', 50)
COGSTransformPack.display_DF_collection(dataframe_mapped_elements_collection_errors, 'WARNING - PLEASE ADDRESS NON-MATCHING REFERENCES:** <br>In the proceeding code cells you need to ensure all transform components are matched to a reference item**!', 50)

In [ ]:
# Join our Slugized transformed data with our REF data - using DataFrames only - no CSV functionality:
# Dependencies: 
def xx__link_REFData_with_Transform__(input_df, source_ref_columns_df: pd.DataFrame, source_ref_components_df: pd.DataFrame):
    
    REFdata_intermediate = pd.merge(input_df, source_ref_columns_df, left_on='REFColumnsCSV Link', right_on='title', how='inner')
    REFdata_linked_successful = pd.merge(REFdata_intermediate, source_ref_components_df, left_on='title', right_on='Label', how='left')
    
    REFdata_linked_UNsuccessful = pd.merge(input_df, source_ref_columns_df, left_on='REFColumnsCSV Link', right_on='title', how='outer', indicator=True).query('_merge=="left_only"')    

    return REFdata_linked_successful, REFdata_linked_UNsuccessful

In [ ]:
# Prepares a copy of the data elements to modify. We need to keep the original data elements for later processing.
# Remember: we're passing collections of DataFrames (which hold the data elements).
# Purpose - useability of Notebooks - reduces loops and complexity.
# The REFColumnsCSV_Link was originally in place as I presumed incorrectly we were matching with Slugized Elements.
# However it is now in place to maintain lineage of the original component name and to hold the synonyms.
# Dependencies:
def xxget_mapped_elements(dataframe_elements_collection):
    dataframe_mapped_elements_collection = {}
    # Prepare mapping in memory component:
    for key in dataframe_elements_collection.keys(): 
        dataframe_mapped_elements_collection[key] = dataframe_elements_collection[key].copy()
        for cols in dataframe_mapped_elements_collection[key][key]:
            idx_temp = dataframe_mapped_elements_collection[key].index[dataframe_mapped_elements_collection[key][key] == cols]
            dataframe_mapped_elements_collection[key].loc[idx_temp, 'REFColumnsCSV Link'] = cols #slug.slug(cols) Not matched on Slugilzed as first believed!

    #Testing:
    #for key in dataframe_mapped_elements_collection.keys():
    #    print('------------TESTING--------------')
    #    display(dataframe_mapped_elements_collection[key])
            
    return dataframe_mapped_elements_collection

In [ ]:
import requests
import json
import re
import urllib.parse
import ntpath

import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet

!Pip install fuzzywuzzy
!Pip install python-Levenshtein
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

from itertools import chain

# Automated mapping of transformed components with the master reference data:
# Dependencies: get_mapped_elements, align_REFdata_with_Transform
def xxmap_REFData_with_Transform(dataframe_elements_collection, df_ref_repo_columns: pd.DataFrame, df_ref_repo_components: pd.DataFrame, dataframe_codelists_collection: pd.DataFrame, execute_flag = 'AutoMap', automap_threshold = 75):

    dataframe_mapped_elements_collection = {}
    dataframe_mapped_elements_collection_errors = {}
    df_recommended_codelists = None
    df_recommended_codelists = pd.DataFrame(columns=['element', 'synonym', 'codelist_path', 'codelist_item', 'synonym_score'])
    df_recommended_codelists.iloc[0:0]
    df_selected_groupedx = df_recommended_codelists.copy()
    
    if execute_flag == 'AutoMap':
        dataframe_mapped_elements_collection = xxget_mapped_elements(dataframe_elements_collection)
    
    if execute_flag != 'AutoMap':
        dataframe_mapped_elements_collection = dataframe_elements_collection
    
    for key in dataframe_mapped_elements_collection.keys():
        df_collection_point, df_collection_point_errors = xx__link_REFData_with_Transform__(dataframe_mapped_elements_collection[key], df_ref_repo_columns, df_ref_repo_components)
        dataframe_mapped_elements_collection[key] = df_collection_point
        display(df_collection_point_errors)
        dataframe_mapped_elements_collection_errors[key] = df_collection_point_errors.loc[:, key:'Entry Type']
        dataframe_mapped_elements_collection_errors[key] = dataframe_mapped_elements_collection_errors[key].reset_index(drop=True)

    post_url_meta = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT * { ?result a skos:ConceptScheme }")
    post_url_meta_results = requests.post(post_url_meta)
    post_url_meta_results_json = json.loads(post_url_meta_results.text)


    i = 0
    lst_REFData_sourceurl = {}
    for key in post_url_meta_results_json['results']['bindings']:
        lst_REFData_sourceurl[i] = (post_url_meta_results_json['results']['bindings'][i]['result']['value'])
        i += 1   

        
    key = None
    for key in dataframe_mapped_elements_collection_errors.keys():
        for idx in dataframe_mapped_elements_collection_errors[key].index:
            str_element = (dataframe_mapped_elements_collection_errors[key][key].loc[idx])
            lst_for_synonyms = []
            lst_for_synonyms_spc = (dataframe_mapped_elements_collection_errors[key][key].loc[idx]).split(' ')
            lst_for_synonyms_uds = "_".join(lst_for_synonyms).split('_')
            lst_for_synonyms = re.findall(r'[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)', dataframe_mapped_elements_collection_errors[key][key].loc[idx]) #CamelCase
            lst_for_synonyms_built = []
            for i in lst_for_synonyms:
                synonyms = []
                for syn in wordnet.synsets(str(i)):
                    for lm in syn.lemmas():
                             synonyms.append(lm.name())#adding into synonyms
            lst_for_synonyms_built = lst_for_synonyms_built + synonyms + lst_for_synonyms_spc + lst_for_synonyms_uds #(set(synonyms))
            lst_for_synonyms_built = list(dict.fromkeys(lst_for_synonyms_built))
            lst_for_synonyms_built.append(dataframe_mapped_elements_collection_errors[key][key].loc[idx])

            for ii in lst_for_synonyms_built:
                for keyz in lst_REFData_sourceurl.keys():
                    int_fuzz_score = fuzz.token_sort_ratio(str(ii), ntpath.basename(lst_REFData_sourceurl[keyz]))
                    if int_fuzz_score >= automap_threshold:
                        post_url_codelist = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("SELECT * WHERE {<" + str(lst_REFData_sourceurl[keyz]) + "> <http://www.w3.org/2004/02/skos/core#member> ?result}")
                        post_url_codelist_results = requests.post(post_url_codelist)
                        post_url_codelist_results_json = json.loads(post_url_codelist_results.text)
                        x = 0
                        lst_codelists_sourceurl = {}
                        for keyy in post_url_codelist_results_json['results']['bindings']:
                            str_next_item = ntpath.basename(post_url_codelist_results_json['results']['bindings'][x]['result']['value'])
                            x += 1
                            df_recommended_codelists = df_recommended_codelists.append({'element' : str_element,'synonym' : str(ii) , 'codelist_path' : lst_REFData_sourceurl[keyz], 'codelist_item' : str_next_item, 'synonym_score' : int_fuzz_score} , ignore_index=True)
    
    df_recommended_codelists.drop_duplicates()
    display(df_recommended_codelists,20000)
    
    for item in dataframe_codelists_collection.keys():
        print(str(item))
        display(dataframe_codelists_collection[item])
    
    for unit in dataframe_elements_collection.keys():
        for (columnName, columnData) in dataframe_elements_collection[unit].iteritems():
            if columnName != 'Entry Type':
                print('Colunm Name : ', columnName)
                print('Column Contents : ', columnData.values)
                lst_processing_values = columnData.values
                for a in lst_processing_values:
                    #print(str(a))
                    if dataframe_codelists_collection[unit].columns.isin([str(a)]).any() == True:
                        lst_processing = dataframe_codelists_collection[unit][str(a)].dropna().tolist()
                        print('Code List Found: ' + str(lst_processing))  
                        df_selected = df_recommended_codelists.loc[df_recommended_codelists['element'] == str(a)]
                        df_selected_grouped = df_selected.groupby(['element', 'synonym', 'codelist_path', 'synonym_score'])['codelist_item'].apply(list).reset_index(name='codelist_item_list')
                        df_selected_grouped['element_codelist'] = (str(lst_processing))
                        # I hate Python lambda:
                        #df_selected_grouped['codelist_score'] = df_selected_grouped.apply(lambda x: fuzz.token_sort_ratio(x['codelist_item_list'].apply(list), x['element_codelist'].apply(list)), axis=1)
                        df_selected_grouped2 = pd.DataFrame(columns=['element', 'synonym', 'codelist_path', 'codelist_score'])
                        for key_grp, value_grp in df_selected_grouped.iterrows():
                            df_selected_grouped2 = df_selected_grouped2.append({'element': df_selected_grouped.loc[key_grp]['element'], 'synonym' : df_selected_grouped.loc[key_grp]['synonym'], 'codelist_path' : df_selected_grouped.loc[key_grp]['codelist_path'], 'codelist_score': (fuzz.token_sort_ratio(df_selected_grouped.loc[key_grp]['codelist_item_list'], df_selected_grouped.loc[key_grp]['element_codelist']))},ignore_index=True) #= ([df_selected_grouped.loc[key_grp]['element'],df_selected_grouped.loc[key_grp]['synonym'],  fuzz.token_sort_ratio(df_selected_grouped.loc[key_grp]['codelist_item_list'], df_selected_grouped.loc[key_grp]['element_codelist'])]) #= codelist_fuzzy_rating
                            df_selected_groupedx = pd.merge(df_selected_grouped, df_selected_grouped2, how='left', on=['element', 'synonym', 'codelist_path'])
                        pd.set_option('max_colwidth', 500)
                        display(df_selected_groupedx)
                        pd.reset_option('max_colwidth')
                        
                        
    return dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors

In [ ]:
# Automated mapping of transformed components with the master reference data:
dataframe_mapped_elements_collection = {}
dataframe_mapped_elements_collection_errors = {}

#dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors =\
#    COGSTransformPack.map_REFData_with_Transform(dataframe_elements_collection,\
#                                                 df_ref_repo_columns, df_ref_repo_components)

print('match on name first or codelist? Need a debug mode on this one? Include matched columns too?')
print('This should not run the same in production!')
print('Sort Render?')

df_recommended_mapped_elements_collection, df_poor_score_mapped_elements_collection =\
    get_REFData_recommendations_for_transforms(dataframe_elements_collection,\
                                                 df_ref_repo_columns, df_ref_repo_components, dataframe_codelists_collection, str_REFDataSPARQLEndPoint = 'http://gss-data.org.uk/sparql.json?query=', component_synonym_threshold = 1, REFData_synonym_threshold = 30, use_local_REPO_REFData = True, debug_mode = True)

COGSTransformPack.display_DF_collection(df_recommended_mapped_elements_collection, 'REFData Recommendations:** <br>Adjust the automap_threshold value to widen your scans (1 = most intensive deep scan)**!', 50)
#COGSTransformPack.display_DF_collection(dataframe_mapped_elements_collection_errors, 'WARNING - PLEASE ADDRESS NON-MATCHING REFERENCES:** <br>In the proceeding code cells you need to ensure all transform components are matched to a reference item**!', 50)

<span style='color:Grey'>
===================================================================================================================</span>

<span style='color:Green'>REFData Recommendation Component Processing:</span>

IntProgress(value=5, description='Total:', max=6)

<span style='color:Blue'>Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.</span>

<span style='color:Blue'>Stage 2/6: Obtain / GET the REFData contents -  Done.</span>

<span style='color:Blue'>Stage 3/6: Get synonyms -  Done..</span>

<span style='color:Blue'>Stage 4/6: Get Code-lists using the obtained synonyms -  Done.</span>

<span style='color:Blue'>Stage 5/6: Match / Align Code-lists with the actual data transforms in-flight -  Done.</span>

<span style='color:Red'>Stage 6/6: Produce Recommendations for the Data Transforms in-flight using local REFData Repositories (if specified) -  In Progress...</span>

,HE - Country level estimates_LE,Entry Type,REFColumnsCSV Link,title,name,component_attachment,property_template,value_template,datatype,value_transformation,regex,range,Label,Description,Component Type,Codelist
0,Period,Dimension,Period,Period,period,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimension#refPeriod,http://reference.data.gov.uk/id/{+period},string,NaN,^(year/[0-9]{4}|gregorian-interval/.*|month/[0-9]{4}-[0-9]{2}|day/[0-9]{4}-[0-9]{2}-[0-9]{2}|quarter/[0-9]{4}-Q[1-4]|government-year/[0-9]{4}-[0-9]{4})$,http://reference.data.gov.uk/def/intervals/Interval,NaN,NaN,NaN,NaN
1,Sex,Dimension,Sex,Sex,sex,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimension#sex,http://purl.org/linked-data/sdmx/2009/code#sex-{sex},string,NaN,^(M|F|T|U|N)$,http://purl.org/linked-data/sdmx/2009/code#Sex,Sex,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/phe-sex

  HE - Country level estimates_LE   Entry Type     REFColumnsCSV Link
0                            Code    Dimension                   Code
1                       age group    Dimension              age group
2           Life Expectancy (LE)_      Measure  Life Expectancy (LE)_
3                    LE Lower CI_  Observation           LE Lower CI_
4                    LE Upper CI_  Observation           LE Upper CI_
5              TransformationType    Dimension     TransformationType

,HE - Country level estimates_HLE,Entry Type,REFColumnsCSV Link,title,name,component_attachment,property_template,value_template,datatype,value_transformation,regex,range,Label,Description,Component Type,Codelist
0,Period,Dimension,Period,Period,period,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimension#refPeriod,http://reference.data.gov.uk/id/{+period},string,NaN,^(year/[0-9]{4}|gregorian-interval/.*|month/[0-9]{4}-[0-9]{2}|day/[0-9]{4}-[0-9]{2}-[0-9]{2}|quarter/[0-9]{4}-Q[1-4]|government-year/[0-9]{4}-[0-9]{4})$,http://reference.data.gov.uk/def/intervals/Interval,NaN,NaN,NaN,NaN
1,Sex,Dimension,Sex,Sex,sex,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimension#sex,http://purl.org/linked-data/sdmx/2009/code#sex-{sex},string,NaN,^(M|F|T|U|N)$,http://purl.org/linked-data/sdmx/2009/code#Sex,Sex,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/phe-sex

,HE - Country level estimates_HLE,Entry Type,REFColumnsCSV Link
0,Code,Dimension,Code
1,age group,Dimension,age group
2,Healthy Life Expectancy (HLE) _,Measure,Healthy Life Expectancy (HLE) _
3,HLE Lower CI_,Observation,HLE Lower CI_
4,HLE Upper CI_,Observation,HLE Upper CI_
5,TransformationType,Dimension,TransformationType

,HE - Region level estimates_LE,Entry Type,REFColumnsCSV Link,title,name,component_attachment,property_template,value_template,datatype,value_transformation,regex,range,Label,Description,Component Type,Codelist
0,Period,Dimension,Period,Period,period,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimension#refPeriod,http://reference.data.gov.uk/id/{+period},string,NaN,^(year/[0-9]{4}|gregorian-interval/.*|month/[0-9]{4}-[0-9]{2}|day/[0-9]{4}-[0-9]{2}-[0-9]{2}|quarter/[0-9]{4}-Q[1-4]|government-year/[0-9]{4}-[0-9]{4})$,http://reference.data.gov.uk/def/intervals/Interval,NaN,NaN,NaN,NaN
1,Sex,Dimension,Sex,Sex,sex,qb:dimension,http://purl.org/linked-data/sdmx/2009/dimension#sex,http://purl.org/linked-data/sdmx/2009/code#sex-{sex},string,NaN,^(M|F|T|U|N)$,http://purl.org/linked-data/sdmx/2009/code#Sex,Sex,NaN,Dimension,http://gss-data.org.uk/def/concept-scheme/phe-sex

  HE - Region level estimates_LE   Entry Type     REFColumnsCSV Link
0                           Code    Dimension                   Code
1                      Age group    Dimension              Age group
2          Life Expectancy (LE)_      Measure  Life Expectancy (LE)_
3                   LE Lower CI_  Observation           LE Lower CI_
4                   LE Upper CI_  Observation           LE Upper CI_
5             TransformationType    Dimension     TransformationType

In [324]:
# Join our Slugized transformed data with our REF data - using DataFrames only - no CSV functionality:
# Dependencies: 
def xxx__link_REFData_with_Transform__(input_df, source_ref_columns_df: pd.DataFrame, source_ref_components_df: pd.DataFrame):
    
    REFdata_intermediate = pd.merge(input_df, source_ref_columns_df, left_on='REFColumnsCSV Link', right_on='title', how='inner')
    REFdata_linked_successful = pd.merge(REFdata_intermediate, source_ref_components_df, left_on='title', right_on='Label', how='left')
    
    REFdata_linked_UNsuccessful = pd.merge(input_df, source_ref_columns_df, left_on='REFColumnsCSV Link', right_on='title', how='outer', indicator=True).query('_merge=="left_only"')    

    return REFdata_linked_successful, REFdata_linked_UNsuccessful

In [694]:
# Join our Slugized transformed data with our REF data - using DataFrames only - no CSV functionality:
# Dependencies: 
def __assign_recommendations_with_inFlight_transforms_using_REPO__(input_df, source_ref_columns_df: pd.DataFrame, source_ref_components_df: pd.DataFrame):

    # Setup:
    df_final_recommendations_matched_with_repo_collection = {}
    df_final_recommendations_NOT_matched_with_repo_collection = {}
    
    for key in input_df.keys():
        
        REFdata_intermediate = pd.merge(input_df[key], source_ref_columns_df, left_on='REFColumnsCSV Link', right_on='title', how='inner')
        df_final_recommendations_matched_with_repo_single = pd.merge(REFdata_intermediate, source_ref_components_df, left_on='title', right_on='Label', how='left')

        df_final_recommendations_NOT_matched_with_repo_single = pd.merge(input_df[key], source_ref_columns_df, left_on='REFColumnsCSV Link', right_on='title', how='outer', indicator=True).query('_merge=="left_only"')    

        df_final_recommendations_matched_with_repo_collection[key] = df_final_recommendations_matched_with_repo_single
        df_final_recommendations_NOT_matched_with_repo_collection[key] = df_final_recommendations_NOT_matched_with_repo_single.loc[:, key:'REFColumnsCSV Link']
        df_final_recommendations_NOT_matched_with_repo_collection[key] = df_final_recommendations_NOT_matched_with_repo_collection[key].reset_index(drop=True)
    
    return df_final_recommendations_matched_with_repo_collection, df_final_recommendations_NOT_matched_with_repo_collection

In [695]:
# Produce Recommendations for the Data Transforms in-flight using local REFData Repositories (if specified):
# Dependencies: 
def __assign_recommendations_with_inFlight_transforms__(dataframe_mapped_elements_collection, source_ref_columns_df: pd.DataFrame = None, source_ref_components_df: pd.DataFrame = None, use_local_REPO_REFData = True):

    if use_local_REPO_REFData == True:
        df_final_recommendations_matched_with_repo_collection, df_final_recommendations_NOT_matched_with_repo_collection = __assign_recommendations_with_inFlight_transforms_using_REPO__(dataframe_mapped_elements_collection, source_ref_columns_df, source_ref_components_df)


    for i in df_final_recommendations_matched_with_repo_collection.keys():
        display(df_final_recommendations_matched_with_repo_collection[i])
        display(df_final_recommendations_NOT_matched_with_repo_collection[i])

#	HE - Country level estimates_LE	Entry Type	REFColumnsCSV Link
#0	Code	Dimension	Code
#1	age group	Dimension	age group
#2	Life Expectancy (LE)_	Measure	Life Expectancy (LE)_
#3	LE Lower CI_	Observation	LE Lower CI_
#4	LE Upper CI_	Observation	LE Upper CI_
#5	TransformationType	Dimension	TransformationType
        time.sleep(10)
    
    #df_final_recommendations_matched_with_repo_collection = None
    #df_final_recommendations_NOT_matched_with_repo_collection = None

    return df_final_recommendations_matched_with_repo_collection, df_final_recommendations_NOT_matched_with_repo_collection

In [696]:
# Match / Align Code-lists with the actual data transforms in flight.
# Dependencies:
def __match_REFData_source_codelists__(dataframe_mapped_elements_collection, dataframe_codelists_collection, df_components_with_synonyms_and_codelists):

    # Setup:
    df_aligned_transforms_and_recommended_codelists = pd.DataFrame(columns=['transform_source', 'component', 'synonym', 'synonym_score', 'codelist_path', 'codelist_score']) #Code-list item
    #df_selected = df_components_with_synonyms_and_codelists
    
    lst_processing_values = []
    
    for unit in dataframe_mapped_elements_collection.keys():
        for (columnName, columnData) in dataframe_mapped_elements_collection[unit].iteritems():
            if columnName == 'REFColumnsCSV Link': #columnName != 'Entry Type':
                #print('Colunm Name : ', columnName, ' from: ' + str(unit))
                #print('Column Contents : ', columnData.values)
                lst_processing_values = columnData.values
                for a in lst_processing_values:
                    #print('lst_processing_values: ' + str(a))
                    lst_processing = []
                    if dataframe_codelists_collection[unit].columns.isin([str(a)]).any() == True:
                        lst_processing = dataframe_codelists_collection[unit][str(a)].dropna().tolist()
                        #print('Code List Found: ' + str(lst_processing))  
                        df_selected = df_components_with_synonyms_and_codelists.loc[df_components_with_synonyms_and_codelists['component'] == str(a)]
                        df_selected_grouped = df_selected.groupby(['component', 'synonym', 'codelist_path', 'synonym_score'])['codelist_item'].apply(list).reset_index(name='codelist_item')
                        df_selected_grouped['element_codelist'] = (str(lst_processing))

                        # I hate Python lambda:
                        #df_selected_grouped['codelist_score'] = df_selected_grouped.apply(lambda x: fuzz.token_sort_ratio(x['codelist_item_list'].apply(list), x['element_codelist'].apply(list)), axis=1)
                        df_selected_grouped2 = pd.DataFrame(columns=['component', 'synonym', 'codelist_path', 'codelist_score'])
                        for key_grp, value_grp in df_selected_grouped.iterrows():
                            df_selected_grouped2 = df_selected_grouped2.append({'transform_source' : str(unit), 'component': df_selected_grouped.loc[key_grp]['component'], 'synonym' : df_selected_grouped.loc[key_grp]['synonym'], 'codelist_path' : df_selected_grouped.loc[key_grp]['codelist_path'], 'codelist_score': (fuzz.token_sort_ratio(df_selected_grouped.loc[key_grp]['codelist_item'], df_selected_grouped.loc[key_grp]['element_codelist']))},ignore_index=True)
                            df_selected_grouped3 = pd.merge(df_selected_grouped, df_selected_grouped2, how='left', on=['component', 'synonym', 'codelist_path'])
                        #pd.set_option('max_colwidth', 500)
                        #display(df_aligned_transforms_and_recommended_codelists)
                        #pd.reset_option('max_colwidth')
        df_aligned_transforms_and_recommended_codelists = pd.concat([df_aligned_transforms_and_recommended_codelists, df_selected_grouped3])
    
    return df_aligned_transforms_and_recommended_codelists

In [697]:
# Using passed SPARQL endpoint component will return the codelists of the the REFData Contents.
# Dependencies:
def __get_REFData_source_codelists_SPARQL__(df_components_with_synonyms, lst_REFData_sourceurl, component_synonym_threshold, REFData_synonym_threshold):

    # Setup:
    df_components_with_synonyms_and_codelists = pd.DataFrame(columns=['component', 'synonym', 'synonym_score', 'codelist_path', 'codelist_item'])
    
    img_prgress_bar_2 = IntProgress(min = 0, max = len(df_components_with_synonyms), description = 'Staging:') #, style = {'description_width': 'initial'}, max_width = 5000) # instantiate the bar
    img_prgress_bar_2.value = 0
    img_prgress_bar_2.bar_style = 'success'
    display(img_prgress_bar_2)
    
    img_label = Label('Ready')
    display(img_label)
    
    #img_prgress_bar_3 = IntProgress(min = 0, max = len(lst_REFData_sourceurl), description = 'Syn. Item:') # instantiate the bar
    #img_prgress_bar_3.value = 0
    #display(img_prgress_bar_3)
    int_progress2 = 0
    
    #display(df_components_with_synonyms) component	synonym
    
    # Double loop - no performance implication on loop order as loop is never broken out:
    for index, row in df_components_with_synonyms.iterrows():
        
        int_progress2 += 1
        img_prgress_bar_2.value = int_progress2
        #img_prgress_bar_2.description = ('Synonym Staging Item: ' + str(row['component']) + ' - ' + str(row['synonym']))
        img_label.value = ('Synonym Staging Item: ' + str(row['component']) + ' - ' + str(row['synonym']))

            
        if int(row['synonym_score']) >= component_synonym_threshold:
            
            int_progress3 = 0
            for keyz in lst_REFData_sourceurl.keys():
                int_REFData_fuzz_score = fuzz.token_sort_ratio(str(row['synonym']), lst_REFData_sourceurl[keyz])
                if int_REFData_fuzz_score >= REFData_synonym_threshold:
                    post_url_codelist = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("SELECT * WHERE {<" + str(lst_REFData_sourceurl[keyz]) + "> <http://www.w3.org/2004/02/skos/core#member> ?result}")
                    post_url_codelist_results = requests.post(post_url_codelist)
                    post_url_codelist_results_json = json.loads(post_url_codelist_results.text)
                    x = 0
                    lst_REFData_item = []
                    for keyy in post_url_codelist_results_json['results']['bindings']:
                        lst_REFData_item.append(ntpath.basename(post_url_codelist_results_json['results']['bindings'][x]['result']['value']))
                        x += 1
                    if len(lst_REFData_item) > 0:
                        df_components_with_synonyms_and_codelists = df_components_with_synonyms_and_codelists.append({'component' : row['component'], 'synonym' : row['synonym'], 'synonym_score' : row['synonym_score'], 'codelist_path' : lst_REFData_sourceurl[keyz], 'codelist_item' : lst_REFData_item} , ignore_index=True)
                #int_progress3 += 1
                #img_prgress_bar_3.value = int_progress3
            
            


    return df_components_with_synonyms_and_codelists

In [698]:
# ?????????????????????????????????????????????.
# Dependencies:
def __get_synonym_REFData_candidates__(dataframe_mapped_elements_collection):

    # Setup:
    df_components_from_collection = pd.DataFrame(columns=['component'])
    df_components_from_collection.iloc[0:0]
    df_components_with_synonyms = pd.DataFrame(columns=['component', 'synonym', 'synonym_score'])
    lst_components_from_collection = []

    for key in dataframe_mapped_elements_collection.keys():
        for idx_col in dataframe_mapped_elements_collection[key].index:
            lst_components_from_collection.append(dataframe_mapped_elements_collection[key][key].loc[idx_col])
    lst_components_from_collection = list(dict.fromkeys(lst_components_from_collection))
    lst_components_from_collection = list(filter(None, lst_components_from_collection))

    
    for item in lst_components_from_collection:
        df_components_from_collection = df_components_from_collection.append({'component' : item} , ignore_index=True)

    for idx_clx in df_components_from_collection.index:
        # Setup:
        lst_for_synonyms_built = []
        # Get RAW component / label / name:
        str_element = (df_components_from_collection['component'].loc[idx_clx])
        # Get Spaced [ ] component / label / name:
        lst_for_synonyms_spc = (df_components_from_collection['component'].loc[idx_clx]).split(' ')
        # Get Underscored [_] component / label / name:
        lst_for_synonyms_uds = (df_components_from_collection['component'].loc[idx_clx]).split('_')
        # Get CamelCased component / label / name:
        lst_for_synonyms = re.findall(r'[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)', df_components_from_collection['component'].loc[idx_clx]) # This is a CamelCase Filter (could be refactored / revised?)
        lst_for_synonyms_built = lst_for_synonyms_built + lst_for_synonyms_spc + lst_for_synonyms_uds + lst_for_synonyms
        lst_for_synonyms_built.append(str(str_element)) # Add into list original component label...
 
        # Unique and Populated:
        lst_for_synonyms_built = list(dict.fromkeys(lst_for_synonyms_built))
        lst_for_synonyms_built = list(filter(None, lst_for_synonyms_built))
        lst_for_synonyms_built = list(filter(lambda myItem: len (myItem) > 2, lst_for_synonyms_built))
        
        # Apply synonyms:
        lst_synonyms = []
        for i in lst_for_synonyms_built:    
            for syn in wordnet.synsets(str(i)):
                for lm in syn.lemmas():
                    lst_synonyms.append(lm.name())
        lst_synonyms_complete = []
        lst_synonyms_complete = lst_synonyms + lst_for_synonyms_built
        lst_synonyms_complete = list(dict.fromkeys(lst_synonyms_complete))
        lst_synonyms_complete = list(filter(None, lst_synonyms_complete))
        
        # Build DataFrame for Return:
        for x in lst_synonyms_complete:
            df_components_with_synonyms = df_components_with_synonyms.append({'component' : str_element, 'synonym' : str(x), 'synonym_score' : fuzz.token_sort_ratio(str_element, str(x))} , ignore_index=True)
            
    return df_components_with_synonyms

In [699]:
# Using passed SPARQL endpoint component will return the contents of the the REFData.
# Dependencies:
def __get_REFData_source_contents_SPARQL__(str_REFDataSPARQLEndPoint):

    # Prepare SPARQL Execution Statement:
    post_url_meta = str_REFDataSPARQLEndPoint + urllib.parse.quote("PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT * { ?result a skos:ConceptScheme }")
    post_url_meta_results = requests.post(post_url_meta)
    post_url_meta_results_json = json.loads(post_url_meta_results.text)

    # Extract Links from JSON Return:
    i = 0
    lst_REFData_sourceurl = {}
    for key in post_url_meta_results_json['results']['bindings']:
        lst_REFData_sourceurl[i] = (post_url_meta_results_json['results']['bindings'][i]['result']['value'])
        i += 1   
 
    return lst_REFData_sourceurl

In [700]:
# Prepares a copy of the data elements to modify. We need to keep the original data elements for later processing.
# Remember: we're passing collections of DataFrames (which hold the data elements).
# Purpose - useability of Notebooks - reduces loops and complexity.
# The REFColumnsCSV_Link was originally in place as I presumed incorrectly we were matching with Slugized Elements.
# However it is now in place to maintain lineage of the original component name and to hold the synonyms.
# Dependencies:
def __get_mapped_elements_link_key__(dataframe_elements_collection):
        
    dataframe_mapped_elements_collection = {}
    # Prepare mapping in memory component:
    for key in dataframe_elements_collection.keys(): 
        dataframe_mapped_elements_collection[key] = dataframe_elements_collection[key].copy()
        for cols in dataframe_mapped_elements_collection[key][key]:
            idx_temp = dataframe_mapped_elements_collection[key].index[dataframe_mapped_elements_collection[key][key] == cols]
            dataframe_mapped_elements_collection[key].loc[idx_temp, 'REFColumnsCSV Link'] = cols #slug.slug(cols) Not matched on Slugilzed as first believed!
            
    return dataframe_mapped_elements_collection

In [701]:
# Basic REFData Display Routine...
# Dependencies:
def __display_REFData_progress__(my_mainPBar_prg = 0, stage_count = 100):
 
    # Setup:
    my_mainPBar_max = stage_count

    # Render this:
    clear_output(wait=True)
    COGSTransformPack.printmd("\n" + "="*115, colour='Grey')
    COGSTransformPack.printmd('REFData Recommendation Component Processing:', colour='Green')
    
    img_prgress_bar_1 = IntProgress(min = 0, max = my_mainPBar_max, description = 'Total:') # instantiate the bar
    img_prgress_bar_1.value = my_mainPBar_prg
    display(img_prgress_bar_1)

    if my_mainPBar_prg == 0:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  In Progress...', colour='Red')
    if my_mainPBar_prg == 1:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 2/6: Obtain / GET the REFData contents -  In Progress...', colour='Red')
    if my_mainPBar_prg == 2:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 2/6: Obtain / GET the REFData contents -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 3/6: Get synonyms -  In Progress...', colour='Red')
    if my_mainPBar_prg == 3:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 2/6: Obtain / GET the REFData contents -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 3/6: Get synonyms -  Done..', colour='Blue')
        COGSTransformPack.printmd('Stage 4/6: Get Code-lists using the obtained synonyms -  In Progress...', colour='Red')
    if my_mainPBar_prg == 4:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 2/6: Obtain / GET the REFData contents -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 3/6: Get synonyms -  Done..', colour='Blue')
        COGSTransformPack.printmd('Stage 4/6: Get Code-lists using the obtained synonyms -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 5/6: Match / Align Code-lists with the actual data transforms in-flight -  In Progress...', colour='Red')
    if my_mainPBar_prg == 5:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 2/6: Obtain / GET the REFData contents -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 3/6: Get synonyms -  Done..', colour='Blue')
        COGSTransformPack.printmd('Stage 4/6: Get Code-lists using the obtained synonyms -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 5/6: Match / Align Code-lists with the actual data transforms in-flight -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 6/6: Produce Recommendations for the Data Transforms in-flight using local REFData Repositories (if specified) -  In Progress...', colour='Red')
    if my_mainPBar_prg == 6:
        COGSTransformPack.printmd('Stage 1/6: Assign REFColumnsCSV Link to dataframe_elements_collection -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 2/6: Obtain / GET the REFData contents -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 3/6: Get synonyms -  Done..', colour='Blue')
        COGSTransformPack.printmd('Stage 4/6: Get Code-lists using the obtained synonyms -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 5/6: Match / Align Code-lists with the actual data transforms in-flight -  Done.', colour='Blue')
        COGSTransformPack.printmd('Stage 6/6: Produce Recommendations for the Data Transforms in-flight using local REFData Repositories (if specified) -  Done.', colour='Blue')

        
    #COGSTransformPack.printmd("\n" + "="*115, colour='Grey')

In [702]:
import requests
import json
import re
import urllib.parse
import ntpath

import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet

!Pip install fuzzywuzzy
!Pip install python-Levenshtein
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

from itertools import chain

from IPython.display import display
from IPython.display import clear_output

from ipywidgets import IntProgress, HBox, Label
import time

# Automated mapping of transformed components with the master reference data:
# Dependencies: get_mapped_elements_link_key, get_REFData_source_contents_SPARQL
def get_REFData_recommendations_for_transforms(dataframe_elements_collection, df_ref_repo_columns: pd.DataFrame, df_ref_repo_components: pd.DataFrame, dataframe_codelists_collection: pd.DataFrame, str_REFDataSPARQLEndPoint = 'http://gss-data.org.uk/sparql.json?query=', component_synonym_threshold = 1, REFData_synonym_threshold = 5, use_local_REPO_REFData = True, debug_mode = False):

    # Setup:
    pd.set_option('max_colwidth', 500)
    pd.set_option("display.max_rows", 2500)    
    my_mainPBar_prg = 0
    stage_count = 6 # Hardcoded - Adjust with the number of stages below:
    

    # Stage 1:
    # Assign REFColumnsCSV Link to dataframe_elements_collection:
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    dataframe_mapped_elements_collection = __get_mapped_elements_link_key__(dataframe_elements_collection)
    my_mainPBar_prg += 1
    
    # Stage 2:
    # Obtain / GET the REFData contents (Return = List):
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    lst_REFData_sourceurl = __get_REFData_source_contents_SPARQL__(str_REFDataSPARQLEndPoint)
    my_mainPBar_prg += 1
    
    # Stage 3:
    # For performance and efficiency we use synonyms to identify possible REFData sources.
    # We therefore only code match on the identified source data lables and their associated synonyms.    
    # Get synonyms:
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    df_components_with_synonyms = __get_synonym_REFData_candidates__(dataframe_mapped_elements_collection)
    my_mainPBar_prg += 1

    # Stage 4:
    # Get Code-lists using the obtained synonyms:
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    df_components_with_synonyms_and_codelists = __get_REFData_source_codelists_SPARQL__(df_components_with_synonyms, lst_REFData_sourceurl, component_synonym_threshold, REFData_synonym_threshold)
    my_mainPBar_prg += 1

    # Stage 5:
    # Match / Align Code-lists with the actual data transforms in-flight:
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    df_aligned_transforms_and_recommended_codelists = __match_REFData_source_codelists__(dataframe_mapped_elements_collection, dataframe_codelists_collection, df_components_with_synonyms_and_codelists)
    my_mainPBar_prg += 1

    # Stage 6:
    # Produce Recommendations for the Data Transforms in-flight using local REFData Repositories (if specified):
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    df_final_recommendations_matched_with_repo_collection = {}
    df_final_recommendations_NOT_matched_with_repo_collection = {}
    df_final_recommendations_matched_with_repo_collection, df_final_recommendations_NOT_matched_with_repo_collection = __assign_recommendations_with_inFlight_transforms__(dataframe_mapped_elements_collection, df_ref_repo_columns, df_ref_repo_components, use_local_REPO_REFData)    
    my_mainPBar_prg += 1
        
    # Final Render:
    __display_REFData_progress(my_mainPBar_prg, stage_count)
    
    
    
    if debug_mode == True:
        for keyz in lst_REFData_sourceurl.keys():
            print('Debug Mode - Sourced & Identified REFData Item: ' + lst_REFData_sourceurl[keyz])
        print('Debug Mode: Displaying Computed Synonyms:')
        display(df_components_with_synonyms)
        print('Debug Mode: Displaying Computed Synonyms Paired Code-lists:')
        display(df_components_with_synonyms_and_codelists)
        print('Debug Mode: Displaying Computed Synonyms Paired Code-lists Aligned to their in-flight Transforms:')
        display(df_aligned_transforms_and_recommended_codelists)    
    
    pd.reset_option('max_colwidth')
    pd.reset_option('display.max_rows')
        
    dataframe_mapped_elements_collection_errors = 0
    return dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors

[nltk_data] Downloading package wordnet to /Users/martyn/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Requirement already satisfied: fuzzywuzzy in /anaconda3/lib/python3.7/site-packages (0.18.0)
Requirement already satisfied: python-Levenshtein in /anaconda3/lib/python3.7/site-packages (0.12.0)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.7/site-packages (from python-Levenshtein) (41.0.1)

In [ ]:











# Automated mapping of transformed components with the master reference data:
# Dependencies: get_mapped_elements, align_REFdata_with_Transform
def xssssssxmap_REFData_with_Transform(dataframe_elements_collection, df_ref_repo_columns: pd.DataFrame, df_ref_repo_components: pd.DataFrame, dataframe_codelists_collection: pd.DataFrame, execute_flag = 'AutoMap', automap_threshold = 75):

    dataframe_mapped_elements_collection = {}
    dataframe_mapped_elements_collection_errors = {}
    df_recommended_codelists = None
    df_recommended_codelists = pd.DataFrame(columns=['element', 'synonym', 'codelist_path', 'codelist_item', 'synonym_score'])
    df_recommended_codelists.iloc[0:0]
    df_selected_groupedx = df_recommended_codelists.copy()
    
    if execute_flag == 'AutoMap':
        dataframe_mapped_elements_collection = xxget_mapped_elements(dataframe_elements_collection)
    
    if execute_flag != 'AutoMap':
        dataframe_mapped_elements_collection = dataframe_elements_collection
    
    for key in dataframe_mapped_elements_collection.keys():
        df_collection_point, df_collection_point_errors = xx__link_REFData_with_Transform__(dataframe_mapped_elements_collection[key], df_ref_repo_columns, df_ref_repo_components)
        dataframe_mapped_elements_collection[key] = df_collection_point
        display(df_collection_point_errors)
        dataframe_mapped_elements_collection_errors[key] = df_collection_point_errors.loc[:, key:'Entry Type']
        dataframe_mapped_elements_collection_errors[key] = dataframe_mapped_elements_collection_errors[key].reset_index(drop=True)

    post_url_meta = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT * { ?result a skos:ConceptScheme }")
    post_url_meta_results = requests.post(post_url_meta)
    post_url_meta_results_json = json.loads(post_url_meta_results.text)


    i = 0
    lst_REFData_sourceurl = {}
    for key in post_url_meta_results_json['results']['bindings']:
        lst_REFData_sourceurl[i] = (post_url_meta_results_json['results']['bindings'][i]['result']['value'])
        i += 1   

        
    key = None
    for key in dataframe_mapped_elements_collection_errors.keys():
        for idx in dataframe_mapped_elements_collection_errors[key].index:
            str_element = (dataframe_mapped_elements_collection_errors[key][key].loc[idx])
            lst_for_synonyms = []
            lst_for_synonyms_spc = (dataframe_mapped_elements_collection_errors[key][key].loc[idx]).split(' ')
            lst_for_synonyms_uds = "_".join(lst_for_synonyms).split('_')
            lst_for_synonyms = re.findall(r'[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)', dataframe_mapped_elements_collection_errors[key][key].loc[idx]) #CamelCase
            lst_for_synonyms_built = []
            for i in lst_for_synonyms:
                synonyms = []
                for syn in wordnet.synsets(str(i)):
                    for lm in syn.lemmas():
                             synonyms.append(lm.name())#adding into synonyms
            lst_for_synonyms_built = lst_for_synonyms_built + synonyms + lst_for_synonyms_spc + lst_for_synonyms_uds #(set(synonyms))
            lst_for_synonyms_built = list(dict.fromkeys(lst_for_synonyms_built))
            lst_for_synonyms_built.append(dataframe_mapped_elements_collection_errors[key][key].loc[idx])

            for ii in lst_for_synonyms_built:
                for keyz in lst_REFData_sourceurl.keys():
                    int_fuzz_score = fuzz.token_sort_ratio(str(ii), ntpath.basename(lst_REFData_sourceurl[keyz]))
                    if int_fuzz_score >= automap_threshold:
                        post_url_codelist = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("SELECT * WHERE {<" + str(lst_REFData_sourceurl[keyz]) + "> <http://www.w3.org/2004/02/skos/core#member> ?result}")
                        post_url_codelist_results = requests.post(post_url_codelist)
                        post_url_codelist_results_json = json.loads(post_url_codelist_results.text)
                        x = 0
                        lst_codelists_sourceurl = {}
                        for keyy in post_url_codelist_results_json['results']['bindings']:
                            str_next_item = ntpath.basename(post_url_codelist_results_json['results']['bindings'][x]['result']['value'])
                            x += 1
                            df_recommended_codelists = df_recommended_codelists.append({'element' : str_element,'synonym' : str(ii) , 'codelist_path' : lst_REFData_sourceurl[keyz], 'codelist_item' : str_next_item, 'synonym_score' : int_fuzz_score} , ignore_index=True)
    
    df_recommended_codelists.drop_duplicates()
    display(df_recommended_codelists,20000)
    
    for item in dataframe_codelists_collection.keys():
        print(str(item))
        display(dataframe_codelists_collection[item])
    
    for unit in dataframe_elements_collection.keys():
        for (columnName, columnData) in dataframe_elements_collection[unit].iteritems():
            if columnName != 'Entry Type':
                print('Colunm Name : ', columnName)
                print('Column Contents : ', columnData.values)
                lst_processing_values = columnData.values
                for a in lst_processing_values:
                    #print(str(a))
                    if dataframe_codelists_collection[unit].columns.isin([str(a)]).any() == True:
                        lst_processing = dataframe_codelists_collection[unit][str(a)].dropna().tolist()
                        print('Code List Found: ' + str(lst_processing))  
                        df_selected = df_recommended_codelists.loc[df_recommended_codelists['element'] == str(a)]
                        df_selected_grouped = df_selected.groupby(['element', 'synonym', 'codelist_path', 'synonym_score'])['codelist_item'].apply(list).reset_index(name='codelist_item_list')
                        df_selected_grouped['element_codelist'] = (str(lst_processing))
                        # I hate Python lambda:
                        #df_selected_grouped['codelist_score'] = df_selected_grouped.apply(lambda x: fuzz.token_sort_ratio(x['codelist_item_list'].apply(list), x['element_codelist'].apply(list)), axis=1)
                        df_selected_grouped2 = pd.DataFrame(columns=['element', 'synonym', 'codelist_path', 'codelist_score'])
                        for key_grp, value_grp in df_selected_grouped.iterrows():
                            df_selected_grouped2 = df_selected_grouped2.append({'element': df_selected_grouped.loc[key_grp]['element'], 'synonym' : df_selected_grouped.loc[key_grp]['synonym'], 'codelist_path' : df_selected_grouped.loc[key_grp]['codelist_path'], 'codelist_score': (fuzz.token_sort_ratio(df_selected_grouped.loc[key_grp]['codelist_item_list'], df_selected_grouped.loc[key_grp]['element_codelist']))},ignore_index=True) #= ([df_selected_grouped.loc[key_grp]['element'],df_selected_grouped.loc[key_grp]['synonym'],  fuzz.token_sort_ratio(df_selected_grouped.loc[key_grp]['codelist_item_list'], df_selected_grouped.loc[key_grp]['element_codelist'])]) #= codelist_fuzzy_rating
                            df_selected_groupedx = pd.merge(df_selected_grouped, df_selected_grouped2, how='left', on=['element', 'synonym', 'codelist_path'])
                        pd.set_option('max_colwidth', 500)
                        display(df_selected_groupedx)
                        pd.reset_option('max_colwidth')
                        
                        
    return dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors

### Stage VI (c): Mapping our Transforms with our Reference Data - Reference / Transform Manual Map:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *We must map / associate our transformed data dimensions with our reference data repository / master database:*
* Load to memory our master reference data.
* Map / associate reference data with our transformed data entities / dimensions.
    * *Note an automated attempt to map is conducted - but manual intervention is likely.*
    * *Mapping between the transformed dimensions (components) and the master reference data is completed manually where the automation routine fails.*

In [ ]:
# Manual mapping of transformed components with the master reference data:
# Iterate Code until all components are Mapped:

# Take a copy so that this cell can be re-run / iterated until all components are mapped:
# This could be factored into the module / function using recursive code; at present the approach is simplified.
dataframe_elements_collection_my_manual_edit = {}
for key in dataframe_elements_collection.keys(): 
    dataframe_elements_collection_my_manual_edit[key] = dataframe_elements_collection[key].copy()
    
# Manual component reference data assignment (where the automated process failed to map or mapped incorrectly):
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'Code', 'ONS Geography')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'age group', 'ONS Age Range')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'Age group', 'ONS Age Range')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'LE Lower CI_', 'Lower CI')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'HLE Lower CI_', 'Lower CI')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'LE Upper CI_', 'Upper CI')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'HLE Upper CI_', 'Upper CI')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'Life Expectancy (LE)_', 'Value')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'Healthy Life Expectancy (HLE) _', 'Value')
COGSTransformPack.assign_reference_data_mapping(dataframe_elements_collection_my_manual_edit,\
                                                'TransformationType', 'Life Expectancy Estimate Type')

dataframe_elements_collection_my_manual_edit = COGSTransformPack.get_mapped_elements(dataframe_elements_collection_my_manual_edit)

# Re-run Component:
dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_errors =\
    COGSTransformPack.map_REFData_with_Transform(dataframe_elements_collection_my_manual_edit,\
                                                 df_ref_repo_columns, df_ref_repo_components, 'Manual')

# Output the results of your manual maps:
mapped_message = "ALL Data Entities Mapped! Looks like you're safe to Proceed!"
if len(dataframe_mapped_elements_collection_errors[key]) > 0:
    error_message = 'WARNING - PLEASE ADDRESS NON-MATCHING REFERENCES:** <br>Please continue iterating your manual edits to ensure all transform components are matched to a reference item**!'
    mapped_message = 'The following components have successfully mapped:'
    COGSTransformPack.display_DF_collection(dataframe_mapped_elements_collection_errors, error_message)
COGSTransformPack.display_DF_collection(dataframe_mapped_elements_collection, mapped_message)

### Stage VI (d): Mapping our Transforms with our Reference Data - Creating the Meta-JSON:

**Purpose:** *To create an RDF output we need the data (.csv) and associated meta data (.json).*

**Description:** *We must map / associate our transformed data dimensions with our reference data repository / master database:*
* Load to memory our master reference data.
* Map / associate reference data with our transformed data entities / dimensions.
    * *Note an automated attempt to map is conducted - but manual intervention is likely.*
    * *Mapping between the transformed dimensions (components) and the master reference data is completed manually where the automation routine fails.*

In [ ]:
dataframe_mapped_elements_collection_names = []
for key in dataframe_mapped_elements_collection.keys():
    dataframe_mapped_elements_collection_names.append(key)

json_meta_data_collection = {}
str_distribution_metadata = str(distribution._properties_metadata)
json_meta_data_collection = COGSTransformPack.create_meta_json(dataframe_mapped_elements_collection, dataframe_mapped_elements_collection_names, str_distribution_metadata)

for key in json_meta_data_collection.keys():
    write_to_file_JSONmetadata = open(COGSTransformPack.slug.slug(key) + '-metadata.json', "w")
    write_to_file_JSONmetadata.write(json_meta_data_collection[key])
    write_to_file_JSONmetadata.close()
    COGSTransformPack.printmd('**Displaying Constructed meta-JSON for: ' + key + ' :**', colour = 'Green')
    print(json_meta_data_collection[key])

### Stage VII: RDF (Resource Description Framework File) Production:

**Purpose:** *To create the RDF output(s).*

**Description:** *Utilising all the components / objects we have so far constructed we can produce the final RDF(s):*
* Until we can process files with the CSVWConverter locally we will utilise GIT for our HTTP requests.
* Map / associate reference data with our transformed data entities / dimensions.
    * *Push related files to GIT for a single output.*
    * *Produce RDF.*
    * *---> Iterate until all of our CSV collection is processed <---*

In [ ]:
# Final step:
COGSTransformPack.create_rdf(dataframe_collection)

### Things to consider:

* **Investigate PropertyURL - is this sourced correctly?**

* **Investigate AboutURL - is this sourced correctly?**

* **What is being done for data markers (eg: NA, Other, See Ref etc.).**

* **Testing strategy needed - how do we manage test data between Publishing revisions?**

* **Fuzzy matching on codelists to suggest appropriate REFData.**

* **Automated matching on component type (dimension, measure or observation) using the REFData?**

* **Integration with Leigh's AirTable-GIT API. For example this document could be generated with the transform names already pre-populated. This may eliminate the issue of tracability we currently have of one-source to multiple-outputs where the lineage is lost through 'unexpected' labels and naming of the outputs etc. Aditionally this API could also update AirTable sources to indicate when the Transform process steps are completed etc. (Design, Transform, REFData and RDF etc.).**

* **RDF Validation and interfacing with Swirl / PMD Platform.**

### Suggestion:

* **Sharing the development and learning activities within the team - Shannon and Mike are looking at GSSUtils and Data Blogs / Visualisations etc. so JJ and Vamshi could maybe help develop components of this Notebook (maybe extracting out to APIs for external publishers long term etc)?**

### Stage IV (b): Data Wrangling Validity of our Transforms in CSV  Format:

**Purpose:** *This stage is intended so that the developer (you) can 'eye-ball' the 'tidy-data' transform.*

**Note:** *This is for human visualisation - not for specific testing (or as part of a testing framework).*

**Important:** *If the transformations appear correct we can proceed, otherwise we need to re-factor the data wrangling stage (Stage III).*

In [ ]:
# Check the validity of the transform(s) in their CSV format.
# display_DF_collection_csv_report will convert the transforms to CSV in memory and perform an analysis.
# You will be warned of any validation failures from the analysis.
COGSTransformPack.display_DF_collection_csv_report(dataframe_collection)

In [100]:
synlst = []
for syn in wordnet.synsets('age'):
    for lm in syn.lemmas():
        synlst.append(lm.name())
print(synlst)

['age', 'historic_period', 'age', 'age', 'eld', 'long_time', 'age', 'years', 'old_age', 'years', 'age', 'eld', 'geezerhood', 'age', 'senesce', 'age', 'get_on', 'mature', 'maturate', 'age']

In [ ]:
!Pip install fuzzywuzzy
!Pip install python-Levenshtein

In [ ]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [ ]:
fuzz.ratio('spoonbarz', 'spoonbar')

In [ ]:
#fuzz.ratio("New York Mets vs Atlanta Braves", "Atlanta Braves vs New York Mets")
#fuzz.partial_ratio("New York Mets vs Atlanta Braves", "Atlanta Braves vs New York Mets")
fuzz.token_sort_ratio("New York Metz vs Atlanta Braves", "Atlanta Braves vs New York Mets")

In [ ]:
#COGSTransformPack.display_DF_collection(dataframe_codelists_collection, 'Codelists (Generated from get_codelists_from_dimensions()):', 20)
import requests
import json
import urllib.parse
import ntpath

url = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("SELECT * WHERE {<http://gss-data.org.uk/def/concept-scheme/ethnic-groups> <http://www.w3.org/2004/02/skos/core#member> ?result}")
print(url)

x = requests.post(url)

print(x.text)

y = json.loads(x.text)

#display(y)
#display(y['results']['bindings'][0]['result']['value'])
#print(ntpath.basename(y['results']['bindings'][0]['result']['value']))

#for key in y['results']['bindings']:
#    print(key)

i = 0
str_REFData_In_Scope = ''
for key in y['results']['bindings']:
    print(y['results']['bindings'][i]['result']['value'])
    print(ntpath.basename(y['results']['bindings'][i]['result']['value']))
    str_REFData_In_Scope = str_REFData_In_Scope + (ntpath.basename(y['results']['bindings'][i]['result']['value'])) + ', '
    i += 1
    

for key in dataframe_codelists_collection.keys():
    for col in dataframe_codelists_collection[key]:
        print(col, key)
        str_codelist = dataframe_codelists_collection[key][col].dropna().values.tolist()
        display(str_codelist)
        fuz_matching_rating = fuzz.token_sort_ratio(str_REFData_In_Scope, str_codelist)
        print('Fuzzy: ' + str(fuz_matching_rating))

# Basic Hacked for 100 Fuzzy Match.
str_REFData_In_Scope = 'E92000001, K02000001'       
for key in dataframe_codelists_collection.keys():
    for col in dataframe_codelists_collection[key]:
        print(col, key)
        str_codelist = dataframe_codelists_collection[key][col].dropna().values.tolist()
        display(str_codelist)
        fuz_matching_rating = fuzz.token_sort_ratio(str_REFData_In_Scope, str_codelist)
        print('Fuzzy: ' + str(fuz_matching_rating))

In [ ]:
post_url_meta = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT * { ?result a skos:ConceptScheme }")
print(url)

x = requests.post(post_url_meta)

#print(x.text)

y = json.loads(x.text)
#display(y)

i = 0
for key in y['results']['bindings']:
    print(y['results']['bindings'][i]['result']['value'])
    print(ntpath.basename(y['results']['bindings'][i]['result']['value']))
    i += 1

#y = json.loads(x.text)

In [ ]:
url = 'http://gss-data.org.uk/sparql.json?query=' + urllib.parse.quote("SELECT * WHERE {<http://gss-data.org.uk/def/concept-scheme/phe-sex> <http://www.w3.org/2004/02/skos/core#member> ?result}")
print(url)

x = requests.post(url)

print(x.text)

y = json.loads(x.text)

#display(y)
#display(y['results']['bindings'][0]['result']['value'])
#print(ntpath.basename(y['results']['bindings'][0]['result']['value']))

#for key in y['results']['bindings']:
#    print(key)

i = 0
for key in y['results']['bindings']:
    print(y['results']['bindings'][i]['result']['value'])
    print(ntpath.basename(y['results']['bindings'][i]['result']['value']))
    i += 1

In [ ]:
for key in dataframe_codelists_collection.keys():
    for col in dataframe_codelists_collection[key]:
        print(col, key)
        str_codelist = dataframe_codelists_collection[key][col].dropna().values.tolist()
        display(str_codelist)

In [ ]:
!pip install PyDictionary
from PyDictionary import PyDictionary

dictionary=PyDictionary()

In [ ]:
print (dictionary.synonym("gender"))

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet

In [ ]:
from nltk.corpus import wordnet
#Creating a list 
synonyms = []
for syn in wordnet.synsets("employment"):
    for lm in syn.lemmas():
             synonyms.append(lm.name())#adding into synonyms
print (set(synonyms))

In [ ]:
!pip install gssutils latest